### ISSUE TITLE
JUnit view doesn't support "aborted" JUnit result

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.ui#1000]
See https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/999.

Please change this "txt" file to "xml" (github doesn't allow to add xml files to ticket)  and try to import into the JUnit view.
[org.eclipse.jdt.ui.tests_ep431I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.txt](https://github.com/eclipse-jdt/eclipse.jdt.ui/files/13645332/org.eclipse.jdt.ui.tests_ep431I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.txt)

An error will be reported:
```
eclipse.buildId=4.31.0.I20231211-1800
java.version=21.0.1
java.vendor=N/A
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -data /data/4x_platform_workspace -os linux -ws gtk -arch x86_64

org.eclipse.jdt.junit
Error
Tue Dec 12 08:41:29 CET 2023
Error

org.eclipse.core.runtime.CoreException: The test run could not be imported from file '/home/aloskuto/Downloads/org.eclipse.jdt.ui.tests_ep431I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.xml'.
	at org.eclipse.jdt.internal.junit.model.JUnitModel.throwImportError(JUnitModel.java:539)
	at org.eclipse.jdt.internal.junit.model.JUnitModel.importTestRunSession(JUnitModel.java:397)
	at org.eclipse.jdt.internal.junit.ui.TestRunnerViewPart$ImportTestRunSessionAction.run(TestRunnerViewPart.java:526)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:581)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:415)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5854)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5064)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4516)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1152)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1043)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:152)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:648)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:555)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1432)
Caused by: org.xml.sax.SAXParseException; systemId: file:/home/aloskuto/Downloads/org.eclipse.jdt.ui.tests_ep431I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.xml; lineNumber: 3199; columnNumber: 104; unknown node 'aborted'
	at org.eclipse.jdt.internal.junit.model.TestRunHandler.startElement(TestRunHandler.java:218)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:518)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:183)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1387)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2726)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:542)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:889)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:825)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:637)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:326)
	at java.xml/javax.xml.parsers.SAXParser.parse(SAXParser.java:330)
	at org.eclipse.jdt.internal.junit.model.JUnitModel.importTestRunSession(JUnitModel.java:392)
	... 29 more
```

I see in JUnit 5 javadoc that there is "ABORTED" state : https://junit.org/junit5/docs/5.0.1/api/org/junit/platform/engine/TestExecutionResult.Status.html

However, in `org.eclipse.jdt.internal.junit.model.IXMLTags` and in the `org.eclipse.jdt.internal.junit.model.TestRunHandler` we don't "know" that state and fail.

We should support that. The simplest workaround is to declare "aborted" as "skipped" and the patch seem to be trivial.

**Comment by iloveeclipse** [comment]
Interestingly, running the very same test from the IDE doesn't show "aborted" but "skipped" state. I guess it is because in the IDE it somehow goes over the vintage engine and that one **is probably remapping** "aborted" to "skipped".

**Comment by fedejeanne** [comment]
> I see in JUnit 5 javadoc that there is "ABORTED" state : https://junit.org/junit5/docs/5.0.1/api/org/junit/platform/engine/TestExecutionResult.Status.html
>
> However, in org.eclipse.jdt.internal.junit.model.IXMLTags and in the org.eclipse.jdt.internal.junit.model.TestRunHandler we don't "know" that state and fail.
>
> We should support that. The simplest workaround is to declare "aborted" as "skipped" and the patch seem to be trivial.

Makes sense since "aborted" doesn't seem to mean "timeout exceeded" (at least not in the IDE), I just tested this with a small test:

```java
@Test(timeout= 100)
public void testWithTimeout() throws Exception {
	Thread.sleep(1000);
}
```

This test **fails** (_i.e._ `org.junit.platform.engine.TestExecutionResult.Status.FAILED`) both with the `JUnit4` runner and with the `Parameterized` runner (at least in the IDE they do so)
