### ISSUE TITLE
TypeFilter: java.lang.IllegalArgumentException at shutdown

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.ui#1093]
logged at the end of QuickFixTestSuite:
```
java.lang.IllegalArgumentException
	at org.eclipse.core.internal.preferences.AbstractScope.getNode(AbstractScope.java:36)
	at org.eclipse.jdt.internal.corext.util.TypeFilter.getPreferenceStore(TypeFilter.java:107)
	at org.eclipse.jdt.internal.corext.util.TypeFilter.dispose(TypeFilter.java:140)
	at org.eclipse.jdt.internal.core.manipulation.JavaManipulationPlugin.stop(JavaManipulationPlugin.java:81)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:893)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.stop(BundleContextImpl.java:885)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.stopWorker0(EquinoxBundle.java:1071)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.stopWorker(EquinoxBundle.java:392)
	at org.eclipse.osgi.container.Module.doStop(Module.java:695)
	at org.eclipse.osgi.container.Module.stop(Module.java:554)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.decStartLevel(ModuleContainer.java:2111)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1981)
	at org.eclipse.osgi.container.SystemModule.stopWorker(SystemModule.java:278)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule.stopWorker(EquinoxBundle.java:222)
	at org.eclipse.osgi.container.Module.doStop(Module.java:695)
	at org.eclipse.osgi.container.Module.stop(Module.java:554)
	at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:209)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:240)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
@robstryker regression from https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/1053

**Comment by robstryker** [comment]
Will investigate.

**Comment by iloveeclipse** [comment]
Not this appears in regular SDK based IDE on shutdown too. 
The error below is reported to log on shutdown:

```
eclipse.buildId=4.31.0.I20240123-1800
java.version=21.0.1
java.vendor=N/A
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -data /data/4x_platform_workspace -os linux -ws gtk -arch x86_64

org.eclipse.jdt.core.manipulation
Error
Wed Jan 24 15:13:31 CET 2024
FrameworkEvent ERROR

org.osgi.framework.BundleException: Exception in org.eclipse.jdt.internal.core.manipulation.JavaManipulationPlugin.stop() of bundle org.eclipse.jdt.core.manipulation.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.stop(BundleContextImpl.java:913)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.stopWorker0(EquinoxBundle.java:1071)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.stopWorker(EquinoxBundle.java:392)
	at org.eclipse.osgi.container.Module.doStop(Module.java:695)
	at org.eclipse.osgi.container.Module.stop(Module.java:554)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.decStartLevel(ModuleContainer.java:2111)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1981)
	at org.eclipse.osgi.container.SystemModule.stopWorker(SystemModule.java:278)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule.stopWorker(EquinoxBundle.java:222)
	at org.eclipse.osgi.container.Module.doStop(Module.java:695)
	at org.eclipse.osgi.container.Module.stop(Module.java:554)
	at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:209)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:240)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.IllegalArgumentException
	at org.eclipse.core.internal.preferences.AbstractScope.getNode(AbstractScope.java:36)
	at org.eclipse.jdt.internal.corext.util.TypeFilter.getPreferenceStore(TypeFilter.java:107)
	at org.eclipse.jdt.internal.corext.util.TypeFilter.dispose(TypeFilter.java:140)
	at org.eclipse.jdt.internal.core.manipulation.JavaManipulationPlugin.stop(JavaManipulationPlugin.java:81)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:893)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:571)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.stop(BundleContextImpl.java:885)
	... 13 more
Root exception:
java.lang.IllegalArgumentException
	at org.eclipse.core.internal.preferences.AbstractScope.getNode(AbstractScope.java:36)
	at org.eclipse.jdt.internal.corext.util.TypeFilter.getPreferenceStore(TypeFilter.java:107)
	at org.eclipse.jdt.internal.corext.util.TypeFilter.dispose(TypeFilter.java:140)
	at org.eclipse.jdt.internal.core.manipulation.JavaManipulationPlugin.stop(JavaManipulationPlugin.java:81)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:893)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:571)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.stop(BundleContextImpl.java:885)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.stopWorker0(EquinoxBundle.java:1071)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.stopWorker(EquinoxBundle.java:392)
	at org.eclipse.osgi.container.Module.doStop(Module.java:695)
	at org.eclipse.osgi.container.Module.stop(Module.java:554)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.decStartLevel(ModuleContainer.java:2111)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1981)
	at org.eclipse.osgi.container.SystemModule.stopWorker(SystemModule.java:278)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule.stopWorker(EquinoxBundle.java:222)
	at org.eclipse.osgi.container.Module.doStop(Module.java:695)
	at org.eclipse.osgi.container.Module.stop(Module.java:554)
	at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:209)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:240)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by iloveeclipse** [comment]
The problem is caused by the fact, that the `JavaManipulation.setPreferenceNodeId(null);` that clears the preference key `org.eclipse.jdt.core.manipulation.JavaManipulation.fgPreferenceNodeId` is called from `org.eclipse.jdt.internal.ui.JavaPlugin.stop(BundleContext)` **on shutdown of UI bundle**, which happens **before** shutdown of `org.eclipse.jdt.core.manipulation` bundle. The code in

**Comment by iloveeclipse** [comment]
I assume change in 27c0b5e57387d0df160a523e6315bdde431f2857 was not correct and should not clear the value of the preference on shutdown of org.eclipse.jdt.core bundle. It would only make sense if someone would shutdown & restart UI bundle in same Eclipse instance, which is most likely not a valid use case (or I'm unaware why that should be valid for org.eclipse.jdt.ui).

I will push a PR fixing that.

**Comment by rgrunber** [comment]
It came from : https://git.eclipse.org/r/c/jdt/eclipse.jdt.ui/+/118209/4#message-e3959a57f82ab1373b13a2b77bd39756383954c5.
> JavaPlugin.stop(BundleContext) should set the pref node id to 'null'.

My guess would be that if JDT UI is shut down, then it should relinquish control of the node and allow other clients to take over. When the node is set, its value cannot be changed unless set to `null` first, and that clients would check whether the node is set before setting it.

Realistically, I can't think of a case where JDT UI would shutdown and other clients would want to set the value themselves.
