### ISSUE TITLE
Random failing MarkOccurrenceTest.markOccurrencesAfterEditorReuse

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.ui#1095]
```
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at org.eclipse.jdt.text.tests.MarkOccurrenceTest$2.condition(MarkOccurrenceTest.java:414)
	at org.eclipse.jdt.text.tests.performance.DisplayHelper.waitForCondition(DisplayHelper.java:79)
	at org.eclipse.jdt.text.tests.MarkOccurrenceTest.assertOccurrences(MarkOccurrenceTest.java:421)
	at org.eclipse.jdt.text.tests.MarkOccurrenceTest.markOccurrencesAfterEditorReuse(MarkOccurrenceTest.java:210)
```
https://ci.eclipse.org/jdt/job/eclipse.jdt.ui-github/job/PR-1086/3/testReport/junit/JdtTextTestSuite%20org.eclipse.jdt.text.tests/MarkOccurrenceTest/markOccurrencesAfterEditorReuse/

**Comment by jukzi** [comment]
may relate to https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/80

**Comment by jukzi** [comment]
can not reproduce locally.

**Comment by stephan-herrmann** [comment]
Seen in a Y-build with exact same symptom: https://ci.eclipse.org/releng/job/YPBuilds/job/ep434Y-unit-cen64-gtk3-java24/8/testReport/org.eclipse.jdt.text.tests/MarkOccurrenceTest/markOccurrencesAfterEditorReuse/
