### ISSUE TITLE
JavaAllCompletionProposalComputer throws a runtime exception

### ISSUE THREAD

**Issue by JVS94** [eclipse-jdt/eclipse.jdt.ui#1163]
The test code is as follows :
```java
import org.eclipse.swt.widgets.Event;
import org.eclipse.swt.widgets.Listener;

public class X {
    
    Listener listener = event -> {
        
        new Listener() {

            
            
            Listener lis = e -> {
                Listener lis = e1 -> {
                    {
                        Listener lis1 = e2 -> {
                        } ;
                    }
                } ;
            } ;
            
            @Override
            public void handleEvent(Event event) {
            }
        } ;
    } ;

}

```
Enter any letter as shown :
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/44021373/4e76df19-f116-4cad-8be0-30ea24eaeb49)

**Comment by jukzi** [comment]
reproducible with
eclipse.buildId=4.31.0.I20240131-1800
java.version=21.0.2 logs
```
java.lang.ClassCastException: class org.eclipse.jdt.internal.compiler.ast.TypeDeclaration cannot be cast to class org.eclipse.jdt.internal.compiler.ast.AbstractVariableDeclaration (org.eclipse.jdt.internal.compiler.ast.TypeDeclaration and org.eclipse.jdt.internal.compiler.ast.AbstractVariableDeclaration are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @2d33bddd)
	at org.eclipse.jdt.internal.compiler.parser.Parser.consumeExitVariableWithoutInitialization(Parser.java:4132)
	at org.eclipse.jdt.internal.codeassist.complete.CompletionParser.consumeExitVariableWithoutInitialization(CompletionParser.java:3042)
	at org.eclipse.jdt.internal.compiler.parser.Parser.consumeRule(Parser.java:6999)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:12659)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:12917)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:12874)
	at org.eclipse.jdt.internal.compiler.parser.Parser.dietParse(Parser.java:11256)
	at org.eclipse.jdt.internal.codeassist.complete.CompletionParser.dietParse(CompletionParser.java:5448)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.complete(CompletionEngine.java:2138)
	at org.eclipse.jdt.internal.core.Openable.codeComplete(Openable.java:135)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeComplete(CompilationUnit.java:360)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeComplete(CompilationUnit.java:350)
	at org.eclipse.jdt.internal.ui.text.java.JavaCompletionProposalComputer.internalComputeCompletionProposals(JavaCompletionProposalComputer.java:256)
	at org.eclipse.jdt.internal.ui.text.java.JavaCompletionProposalComputer.computeCompletionProposals(JavaCompletionProposalComputer.java:218)
	at org.eclipse.jdt.internal.ui.text.java.JavaTypeCompletionProposalComputer.computeCompletionProposals(JavaTypeCompletionProposalComputer.java:65)
	at org.eclipse.jdt.internal.ui.text.java.CompletionProposalComputerDescriptor.computeCompletionProposals(CompletionProposalComputerDescriptor.java:354)
	at org.eclipse.jdt.internal.ui.text.java.CompletionProposalCategory.computeCompletionProposals(CompletionProposalCategory.java:340)
	at org.eclipse.jdt.internal.ui.text.java.ContentAssistProcessor.collectProposals(ContentAssistProcessor.java:333)
	at org.eclipse.jdt.internal.ui.text.java.ContentAssistProcessor.computeCompletionProposals(ContentAssistProcessor.java:289)
	at org.eclipse.jface.text.contentassist.AsyncCompletionProposalPopup.lambda$10(AsyncCompletionProposalPopup.java:378)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.jface.text.contentassist.AsyncCompletionProposalPopup.lambda$9(AsyncCompletionProposalPopup.java:377)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

```
