### ISSUE TITLE
ParameterNamesCodeMiningTest fails on I Builds

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.ui#1236]
on most platforms
for example https://download.eclipse.org/eclipse/downloads/drops4/I20240306-1800/testresults/html/org.eclipse.jdt.text.tests_ep432I-unit-cen64-gtk3-java21_linux.gtk.x86_64_21.html
```
java.lang.AssertionError: Occurence annotation not added

at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.eclipse.jdt.text.tests.codemining.ParameterNamesCodeMiningTest.testCollapsedFoldingAndToggleHighlight(ParameterNamesCodeMiningTest.java:272)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
```

**Comment by iloveeclipse** [comment]
This is a regression from https://github.com/eclipse-platform/eclipse.platform.ui/pull/1703.

Please check whether the change or the test need to be fixed.

**Comment by jukzi** [comment]
I can reproduce it, but don't know yet how to fix. The firePostSelectionChanged is send (immediatly instead of after a delay ini this case), but somehow that does not work in this case. May be some concurrency issue that was just did show up yet. i will investigate.

**Comment by jukzi** [comment]
to be fixed by https://github.com/eclipse-platform/eclipse.platform.ui/pull/1738
