### ISSUE TITLE
Cleanup: "Convert String to TextBlock" super slow

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.ui#1237]
cleaning up jdt.ui itself hangs at CleanUpTest.java:
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/34d6c468-c388-48ad-b96a-d0ad863c6842)![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/b151b5dd-79cf-47a3-bbd2-7eaeb6c930f6)

jstack:

```
ModalContext" #30732 [2868] prio=6 os_prio=0 cpu=192796.88ms elapsed=196.60s tid=0x000001bf828d37a0 nid=2868 runnable  [0x00000089a20fd000]
   java.lang.Thread.State: RUNNABLE
        at org.eclipse.jdt.internal.compiler.parser.Scanner.scanForStringLiteral(Scanner.java:1964)
        at org.eclipse.jdt.internal.compiler.parser.Scanner.getNextToken0(Scanner.java:1505)
        at org.eclipse.jdt.internal.compiler.parser.Scanner.getNextToken(Scanner.java:1233)
        at org.eclipse.jdt.internal.core.util.PublicScanner.getNextToken(PublicScanner.java:117)
        at org.eclipse.jdt.internal.corext.refactoring.nls.NLSScanner.scan(NLSScanner.java:202)
        at org.eclipse.jdt.internal.corext.refactoring.nls.NLSScanner.scan(NLSScanner.java:56)
        at org.eclipse.jdt.internal.corext.refactoring.nls.NLSUtil.scanCurrentLine(NLSUtil.java:158)
        at org.eclipse.jdt.internal.corext.fix.StringConcatToTextBlockFixCore$StringConcatFinder.visit(StringConcatToTextBlockFixCore.java:170)
        at org.eclipse.jdt.core.dom.InfixExpression.accept0(InfixExpression.java:353)
        at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3300)
        at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:3348)
        at org.eclipse.jdt.core.dom.VariableDeclarationFragment.accept0(VariableDeclarationFragment.java:238)
        at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3300)
        at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:3371)
        at org.eclipse.jdt.core.dom.VariableDeclarationStatement.accept0(VariableDeclarationStatement.java:254)
        at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3300)
        at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:3371)
        at org.eclipse.jdt.core.dom.Block.accept0(Block.java:128)
        at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3300)
        at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:3348)
        at org.eclipse.jdt.core.dom.MethodDeclaration.accept0(MethodDeclaration.java:677)
        at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3300)
        at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:3371)
        at org.eclipse.jdt.core.dom.TypeDeclaration.accept0(TypeDeclaration.java:498)
        at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3300)
        at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:3371)
        at org.eclipse.jdt.core.dom.CompilationUnit.accept0(CompilationUnit.java:258)
        at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3300)
        at org.eclipse.jdt.internal.corext.fix.StringConcatToTextBlockFixCore.createCleanUp(StringConcatToTextBlockFixCore.java:792)
        at org.eclipse.jdt.internal.ui.fix.StringConcatToTextBlockCleanUpCore.createFix(StringConcatToTextBlockCleanUpCore.java:55)
        at org.eclipse.jdt.internal.ui.fix.AbstractCleanUpCoreWrapper.createFix(AbstractCleanUpCoreWrapper.java:52)
        at org.eclipse.jdt.internal.corext.fix.CleanUpRefactoring.calculateChange(CleanUpRefactoring.java:773)
        at org.eclipse.jdt.internal.corext.fix.CleanUpRefactoring$CleanUpASTRequestor.calculateSolutions(CleanUpRefactoring.java:302)
        at org.eclipse.jdt.internal.corext.fix.CleanUpRefactoring$CleanUpASTRequestor.acceptAST(CleanUpRefactoring.java:280)
        at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:1009)
        at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:692)
        at org.eclipse.jdt.core.dom.ASTParser.createASTs(ASTParser.java:954)
        at org.eclipse.jdt.internal.corext.dom.ASTBatchParser.createASTs(ASTBatchParser.java:83)
        at org.eclipse.jdt.internal.corext.fix.CleanUpRefactoring$CleanUpFixpointIterator.next(CleanUpRefactoring.java:400)
        at org.eclipse.jdt.internal.corext.fix.CleanUpRefactoring.cleanUpProject(CleanUpRefactoring.java:683)
        at org.eclipse.jdt.internal.corext.fix.CleanUpRefactoring.checkFinalConditions(CleanUpRefactoring.java:643)
        at org.eclipse.ltk.core.refactoring.CheckConditionsOperation.run(CheckConditionsOperation.java:86)
        at org.eclipse.ltk.core.refactoring.CreateChangeOperation.run(CreateChangeOperation.java:116)
        at org.eclipse.ltk.core.refactoring.PerformChangeOperation.run(PerformChangeOperation.java:207)
        at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2448)
        at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2473)
        at org.eclipse.ltk.internal.ui.refactoring.WorkbenchRunnableAdapter.run(WorkbenchRunnableAdapter.java:89)
        at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:124)
```

the CleanUp can also not be stopped at that state, i have to kill the JVM

**Comment by jukzi** [comment]
same happens when i try to clean up jdt.core  it hangs at GenericTypeTest.java
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/979506ca-4279-4167-a225-fe0c8dc89bdd)

**Comment by iloveeclipse** [comment]
Could be a recent regression?
@jukzi : can you try to go back on JDT UI changes to 4.31 and test?
Same for JDT core.

@jjohnstn : could you please check?

**Comment by jukzi** [comment]
turns out it is only super slow: ~8 min for the single class
org.eclipse.jdt.ui.tests.quickfix.CleanUpTest
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/ea727a3d-7f60-4840-bbd6-fabe3dd935f8)

**Comment by jjohnstn** [comment]
@iloveeclipse Looking into it

**Comment by iloveeclipse** [comment]
This one, https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1240 and https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1238 probably are one issue, I guess some offsets are not properly computed, so it loops too much and produces some bad artifacts.

**Comment by jjohnstn** [comment]
I've got a fix to remove the NLS checking when none of the comments have NLS markers in them.  Currently, it looks for evidence of trailing comments and then does the NLS parsing.  That should make it run faster.  In CleanUpTest, all the strings have empty line comments.

**Comment by jjohnstn** [comment]
I also found that the NLSUtil.scanCurrentLine() actually scans the entire compilation unit and then finds the NLSLine with the given position.  This means that a full scan is performed for each StringLiteral in the concatenation.  As the CleanUpTest.java file is very large, this really lags.  I have posted a fix which also stops using NLSUtil.scanCurrentLine() and only scans the text of the line.

**Comment by jukzi** [comment]
I confirm the performance i much better now, thanks  @jjohnstn !
