### ISSUE TITLE
IndexOutOfBoundsException when @throws in javadoc doesn't have anything after it

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-jdt/eclipse.jdt.ui#1241]
Consider a simple class like this:

```java
package my.simple;
public class Simple {
	/**
	 * @throws CoreException
	 * @throws
	 */
	public void method() throws Exception {
		
	}
}
```

and click on `Exception` or `CoreException` and a pop-up is displayed like this: 
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/679236/ec9e4851-3126-4afc-8b6b-615b23ccdd39) (full stack trace of the error in the below details block)

I think the error is in this line that assumes there is at least one fragment after the `@throws`:

https://github.com/eclipse-jdt/eclipse.jdt.ui/blob/058aa866e3ea31dd9848bfcb00070c3037b01860/org.eclipse.jdt.core.manipulation/core%20extension/org/eclipse/jdt/internal/core/manipulation/search/ExceptionOccurrencesFinder.java#L288

I reproduced this with 4.32 I-build SDK-I20240307-0940.

<details><summary>Full Stack Trace</summary>
<p>

```
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:361)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at org.eclipse.jdt.core.dom.ASTNode$NodeList.get(ASTNode.java:1583)
	at org.eclipse.jdt.internal.core.manipulation.search.ExceptionOccurrencesFinder.visit(ExceptionOccurrencesFinder.java:288)
	at org.eclipse.jdt.core.dom.MethodDeclaration.accept0(MethodDeclaration.java:653)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3269)
	at org.eclipse.jdt.internal.core.manipulation.search.ExceptionOccurrencesFinder.performSearch(ExceptionOccurrencesFinder.java:144)
	at org.eclipse.jdt.internal.core.manipulation.search.ExceptionOccurrencesFinder.getOccurrences(ExceptionOccurrencesFinder.java:202)
	at org.eclipse.jdt.internal.ui.javaeditor.JavaEditor.updateOccurrenceAnnotations(JavaEditor.java:3312)
	at org.eclipse.jdt.internal.ui.javaeditor.JavaEditor$ActivationListener.windowActivated(JavaEditor.java:1218)
	at org.eclipse.ui.internal.Workbench$8.run(Workbench.java:1031)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.ui.internal.Workbench.fireWindowActivated(Workbench.java:1028)
	at org.eclipse.ui.internal.WorkbenchWindow$6.shellActivated(WorkbenchWindow.java:2462)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:92)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5854)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1555)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1534)
	at org.eclipse.swt.widgets.Shell.gtk_focus_in_event(Shell.java:1602)
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:2505)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:6883)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6162)
	at org.eclipse.swt.internal.gtk3.GTK3.gtk_main_do_event(Native Method)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1597)
	at org.eclipse.swt.internal.gtk3.GTK3.gtk_main_iteration_do(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4513)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:648)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:555)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1432)

``` 

</p>
</details>

**Comment by jukzi** [comment]
i will take a look

**Comment by jukzi** [comment]
the most annoying thing about the bug is, that when i click "OK" the popups open again. endless.

**Comment by jukzi** [comment]
@jonahgraham Thanks for the high quality bug report.
