### ISSUE TITLE
AdvancedJUnitLaunchConfigurationDelegateTest fails on win

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.ui#1248]
```
Illegal char <"> at index 0: "C:\Users\GENIE~1.REL\AppData\Local\Temp\testNames927039289642177752.txt"

java.nio.file.InvalidPathException: Illegal char <"> at index 0: "C:\Users\GENIE~1.REL\AppData\Local\Temp\testNames927039289642177752.txt"
at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
at java.base/java.nio.file.Path.of(Path.java:147)
at java.base/java.nio.file.Paths.get(Paths.java:69)
at org.eclipse.jdt.junit.launcher.AdvancedJUnitLaunchConfigurationDelegateTest.showCommandLineAndExtractContentOfTestNameFile(AdvancedJUnitLaunchConfigurationDelegateTest.java:196)
at org.eclipse.jdt.junit.launcher.AdvancedJUnitLaunchConfigurationDelegateTest.runTestsInSourceFolderOnlyUsesTopLevelClasses(AdvancedJUnitLaunchConfigurationDelegateTest.java:170)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```
see https://download.eclipse.org/eclipse/downloads/drops4/I20240310-1800/testresults/html/org.eclipse.jdt.ui.tests_ep432I-unit-win32-java17_win32.win32.x86_64_17.html

regression from https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/1066
@erik-brangs can you please take a look?

**Comment by erik-brangs** [comment]
Yes, I will take a look.

I suppose the easiest approach would be to just remove the `"` from the start and the end when parsing the argument file in the test on Windows. The `"` seem to be added unconditionally in `exec` in `AbstractVMRunner`.

I will try this out when I have a dev environment Windows. I tried the Oomph setup but it failed with some exceptions about a missing instance variable so I'll have to do it by hand.
