### ISSUE TITLE
jdt.ui.tests.refactoring DNF since I20240331-1800

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.ui#1315]
See https://download.eclipse.org/eclipse/downloads/drops4/I20240331-1800/testResults.php and all following builds.

Note that the build logs for **all** JDT **UI** related bundles is multiple megabytes, while usually below one MB:

https://download.eclipse.org/eclipse/downloads/drops4/I20240404-1800/logs.php#console

![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/964108/4a9b842c-ca65-4228-b1a2-aa4945233f46)

old log from https://download.eclipse.org/eclipse/downloads/drops4/I20240330-1800/logs.php#console

![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/964108/820b6e02-4950-48fc-9f35-6889160cfae5)

In the logs I see no real errors, but tons (~ 15.000 times) of stack traces reported by UI freeze monitor on `JavaProjectHelper.delete()` that hangs in ` org.eclipse.swt.internal.ole.win32.ITaskbarList3.SetOverlayIcon(ITaskbarList3.java:31)` (why UI freeze monitor is not disabled during tests???):

```
!ENTRY org.eclipse.ui.monitoring 2 0 2024-04-01 05:27:24.168
!MESSAGE UI freeze of 0.84s at 05:27:23.329
!SUBENTRY 1 org.eclipse.ui.monitoring 1 0 2024-04-01 05:27:24.168
!MESSAGE Sample at 05:27:23.736 (+0.407s)
Thread 'main' tid=1 (RUNNABLE)
!STACK 0
Stack Trace
	at org.eclipse.swt.internal.ole.win32.COM.VtblCall(Native Method)
	at org.eclipse.swt.internal.ole.win32.ITaskbarList3.SetOverlayIcon(ITaskbarList3.java:31)
	at org.eclipse.swt.widgets.TaskItem.updateImageAndText(TaskItem.java:219)
	at org.eclipse.swt.widgets.TaskItem.setOverlayImage(TaskItem.java:330)
	at org.eclipse.ui.internal.progress.TaskBarProgressManager.updateImage(TaskBarProgressManager.java:162)
	at org.eclipse.ui.internal.progress.TaskBarProgressManager$1.runInUIThread(TaskBarProgressManager.java:120)
	at org.eclipse.ui.progress.UIJob.lambda$0(UIJob.java:148)
	at org.eclipse.ui.progress.UIJob$$Lambda$836/0x000000080132f6a0.run(Unknown Source)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4047)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3663)
	at org.eclipse.jdt.testplugin.JavaProjectHelper.emptyDisplayLoop(JavaProjectHelper.java:1225)
	at org.eclipse.jdt.testplugin.JavaProjectHelper.delete(JavaProjectHelper.java:572)
	at org.eclipse.jdt.ui.tests.refactoring.rules.RefactoringTestSetup.after(RefactoringTestSetup.java:88)
```

**Comment by iloveeclipse** [comment]
I've checked stack traces, they all look "innocent" and doesn't point to any recent change in the code.
I assume Windows test machine is in some bad state and needs a restart.

**Comment by iloveeclipse** [comment]
Pinged IT team at https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4410

**Comment by iloveeclipse** [comment]
Fixed by machine restart
