### ISSUE TITLE
SemanticHighlightingTest.enumHighlighting test failed 

### ISSUE THREAD

**Issue by noopur2507** [eclipse-jdt/eclipse.jdt.ui#1432]
I20240529-1800
win32-java17

org.eclipse.jdt.text.tests.SemanticHighlightingTest
enumHighlighting

The above test failed with this exception:

```
expected:<1> but was:<2>

java.lang.AssertionError: expected:<1> but was:<2>
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.failNotEquals(Assert.java:835)
at org.junit.Assert.assertEquals(Assert.java:647)
at org.junit.Assert.assertEquals(Assert.java:633)
at org.eclipse.jdt.text.tests.AbstractSemanticHighlightingTest.assertEqualPositions(AbstractSemanticHighlightingTest.java:113)
at org.eclipse.jdt.text.tests.SemanticHighlightingTest.enumHighlighting(SemanticHighlightingTest.java:270)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

**Comment by jukzi** [comment]
failed again
https://download.eclipse.org/eclipse/downloads/drops4/I20241215-1800/testresults/html/org.eclipse.jdt.text.tests_ep435I-unit-macosx-x86_64-java17_macosx.cocoa.x86_64_17.html

**Comment by trancexpress** [comment]
Probably a related fail here: https://download.eclipse.org/eclipse/downloads/drops4/I20260430-1800/testresults/html/org.eclipse.jdt.text.tests_ep440I-unit-linux-x86_64-java26_linux.gtk.x86_64_26.html

```
expected: <7> but was: <8>

org.opentest4j.AssertionFailedError: expected: <7> but was: <8>
at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:531)
at org.eclipse.jdt.text.tests.AbstractSemanticHighlightingTest.assertEqualPositions(AbstractSemanticHighlightingTest.java:124)
at org.eclipse.jdt.text.tests.semantictokens.SemanticTokensProviderTest.disabledHighlightingNoError(SemanticTokensProviderTest.java:81)
at java.base/java.lang.reflect.Method.invoke(Method.java:565)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1612)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1612) 
```

**Comment by BoykoAlex** [comment]
Somehow I missed this completely and only reading this now. My only guess is somehow there is a highlighting produced for `T` which should have been a CLASS token the highlighting for which is disabled... Is this reliably reproducible?

**Comment by trancexpress** [comment]
Doesn't look like it, I've been monitoring tests for a month now and I think I only see it now.

**Comment by trancexpress** [comment]
Also a fail in `fieldHighlighting`: https://download.eclipse.org/eclipse/downloads/drops4/I20260601-1800/testresults/html/org.eclipse.jdt.text.tests_ep441I-unit-macosx-aarch64-java21_macosx.cocoa.aarch64_21.html

```
Expected: [offset: 119, length: 5, offset: 138, length: 11, offset: 162, length: 10, offset: 195, length: 16, offset: 553, length: 15, offset: 628, length: 15, offset: 771, length: 6, offset: 798, length: 11, offset: 823, length: 5, offset: 836, length: 17, offset: 862, length: 11, offset: 881, length: 16, offset: 911, length: 10, offset: 929, length: 22, offset: 960, length: 16, offset: 1247, length: 14, offset: 1263, length: 5], actual: [offset: 119, length: 5, offset: 119, length: 5, offset: 138, length: 11, offset: 138, length: 11, offset: 162, length: 10, offset: 162, length: 10, offset: 195, length: 16, offset: 195, length: 16, offset: 553, length: 15, offset: 553, length: 15, offset: 628, length: 15, offset: 628, length: 15, offset: 771, length: 6, offset: 771, length: 6, offset: 798, length: 11, offset: 798, length: 11, offset: 823, length: 5, offset: 823, length: 5, offset: 836, length: 17, offset: 836, length: 17, offset: 862, length: 11, offset: 862, length: 11, offset: 881, length: 16, offset: 881, length: 16, offset: 911, length: 10, offset: 911, length: 10, offset: 929, length: 22, offset: 929, length: 22, offset: 960, length: 16, offset: 960, length: 16, offset: 1247, length: 14, offset: 1247, length: 14, offset: 1263, length: 5, offset: 1263, length: 5] ==> expected: <17> but was: <34>

org.opentest4j.AssertionFailedError: Expected: [offset: 119, length: 5, offset: 138, length: 11, offset: 162, length: 10, offset: 195, length: 16, offset: 553, length: 15, offset: 628, length: 15, offset: 771, length: 6, offset: 798, length: 11, offset: 823, length: 5, offset: 836, length: 17, offset: 862, length: 11, offset: 881, length: 16, offset: 911, length: 10, offset: 929, length: 22, offset: 960, length: 16, offset: 1247, length: 14, offset: 1263, length: 5], actual: [offset: 119, length: 5, offset: 119, length: 5, offset: 138, length: 11, offset: 138, length: 11, offset: 162, length: 10, offset: 162, length: 10, offset: 195, length: 16, offset: 195, length: 16, offset: 553, length: 15, offset: 553, length: 15, offset: 628, length: 15, offset: 628, length: 15, offset: 771, length: 6, offset: 771, length: 6, offset: 798, length: 11, offset: 798, length: 11, offset: 823, length: 5, offset: 823, length: 5, offset: 836, length: 17, offset: 836, length: 17, offset: 862, length: 11, offset: 862, length: 11, offset: 881, length: 16, offset: 881, length: 16, offset: 911, length: 10, offset: 911, length: 10, offset: 929, length: 22, offset: 929, length: 22, offset: 960, length: 16, offset: 960, length: 16, offset: 1247, length: 14, offset: 1247, length: 14, offset: 1263, length: 5, offset: 1263, length: 5] ==> expected: <17> but was: <34>
at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:563)
at org.eclipse.jdt.text.tests.AbstractSemanticHighlightingTest.assertEqualPositions(AbstractSemanticHighlightingTest.java:126)
at org.eclipse.jdt.text.tests.SemanticHighlightingTest.fieldHighlighting(SemanticHighlightingTest.java:94)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) 
```

Nothing in the workspace log: https://download.eclipse.org/eclipse/downloads/drops4/I20260601-1800/testresults/ep441I-unit-macosx-aarch64-java21_macosx.cocoa.aarch64_21/org.eclipse.jdt.text.tests.JdtTextTestSuite.txt

```
!ENTRY org.eclipse.jdt.ui.tests 1 0 2026-06-02 00:11:51.674
!MESSAGE fieldHighlighting() STARTING

!ENTRY org.eclipse.jdt.ui.tests 1 0 2026-06-02 00:11:52.319
!MESSAGE fieldHighlighting() DONE: FAILED
```
