### ISSUE TITLE
JavaLeakTest fails since I20240608

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.ui#1444]
16 fails on all OS:
for example
```
Expected instance count: 0, actual: 1 Element 0 org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitEditor org.eclipse.ui.texteditor.FindReplaceAction#fWorkbenchPart -> org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitEditor@4ad0d464 org.eclipse.ui.texteditor.FindReplaceAction$1#this$0 -> org.eclipse.ui.texteditor.FindReplaceAction@5701c504 java.lang.Object[3] -> org.eclipse.ui.texteditor.FindReplaceAction$1@5cd4c384 org.eclipse.core.runtime.ListenerList#listeners -> [Ljava.lang.Object;@1157443d org.eclipse.core.internal.preferences.EclipsePreferences#preferenceChangeListeners -> [org.eclipse.ui.preferences.ScopedPreferenceStore$$Lambda$307/0x0000000800ed7848@66c3c813, org.ecli java.util.concurrent.ConcurrentHashMap$Node#val -> /instance/org.eclipse.ui.editors java.util.concurrent.ConcurrentHashMap$Node[35] -> org.eclipse.ui.editors=/instance/org.eclipse.ui.editors java.util.concurrent.ConcurrentHashMap#table -> [Ljava.util.concurrent.ConcurrentHashMap$Node;@3c8bdde7 org.eclipse.core.internal.preferences.EclipsePreferences#children -> {org.eclipse.ant.ui=/instance/org.eclipse.ant.ui, org.eclipse.core.expressions=/instance/org.eclips org.eclipse.core.internal.preferences.legacy.PreferenceForwarder#pluginRoot -> /instance org.eclipse.core.runtime.Plugin#preferences -> PreferenceForwarder(org.eclipse.core.resources) org.eclipse.osgi.internal.framework.BundleContextImpl#activator -> org.eclipse.core.resources java.lang.Object[3] -> org.eclipse.osgi.internal.framework.BundleContextImpl@6843d9a java.util.ArrayList#elementData -> [Ljava.lang.Object;@3de8e614 org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl#contextsUsing -> [org.eclipse.osgi.internal.framework.BundleContextImpl@5446f7f5, org.eclipse.osgi.internal.framewor org.eclipse.osgi.internal.location.BasicLocation#serviceRegistration -> {org.eclipse.osgi.service.datalocation.Location}={service.id=8, service.bundleid=0, service.scope=s org.eclipse.osgi.internal.location.EquinoxLocations#instanceLocation -> org.eclipse.osgi.internal.location.BasicLocation@34db5935 org.eclipse.osgi.internal.framework.EquinoxConfiguration#equinoxLocations -> org.eclipse.osgi.internal.location.EquinoxLocations@621a7d83 org.eclipse.osgi.internal.loader.EquinoxClassLoader#configuration -> org.eclipse.osgi.internal.framework.EquinoxConfiguration@674b2703 org.eclipse.osgi.internal.loader.EquinoxClassLoader -> org.eclipse.osgi.internal.loader.EquinoxClassLoader@409a7dc3[org.eclipse.jdt.ui.tests:3.15.500.v202 . Actual: 0

java.lang.AssertionError: Expected instance count: 0, actual: 1
Element 0
org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitEditor
org.eclipse.ui.texteditor.FindReplaceAction#fWorkbenchPart -> org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitEditor@4ad0d464
org.eclipse.ui.texteditor.FindReplaceAction$1#this$0 -> org.eclipse.ui.texteditor.FindReplaceAction@5701c504
java.lang.Object[3] -> org.eclipse.ui.texteditor.FindReplaceAction$1@5cd4c384
org.eclipse.core.runtime.ListenerList#listeners -> [Ljava.lang.Object;@1157443d
org.eclipse.core.internal.preferences.EclipsePreferences#preferenceChangeListeners -> [org.eclipse.ui.preferences.ScopedPreferenceStore$$Lambda$307/0x0000000800ed7848@66c3c813, org.ecli
java.util.concurrent.ConcurrentHashMap$Node#val -> /instance/org.eclipse.ui.editors
java.util.concurrent.ConcurrentHashMap$Node[35] -> org.eclipse.ui.editors=/instance/org.eclipse.ui.editors
java.util.concurrent.ConcurrentHashMap#table -> [Ljava.util.concurrent.ConcurrentHashMap$Node;@3c8bdde7
org.eclipse.core.internal.preferences.EclipsePreferences#children -> {org.eclipse.ant.ui=/instance/org.eclipse.ant.ui, org.eclipse.core.expressions=/instance/org.eclips
org.eclipse.core.internal.preferences.legacy.PreferenceForwarder#pluginRoot -> /instance
org.eclipse.core.runtime.Plugin#preferences -> PreferenceForwarder(org.eclipse.core.resources)
org.eclipse.osgi.internal.framework.BundleContextImpl#activator -> org.eclipse.core.resources
java.lang.Object[3] -> org.eclipse.osgi.internal.framework.BundleContextImpl@6843d9a
java.util.ArrayList#elementData -> [Ljava.lang.Object;@3de8e614
org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl#contextsUsing -> [org.eclipse.osgi.internal.framework.BundleContextImpl@5446f7f5, org.eclipse.osgi.internal.framewor
org.eclipse.osgi.internal.location.BasicLocation#serviceRegistration -> {org.eclipse.osgi.service.datalocation.Location}={service.id=8, service.bundleid=0, service.scope=s
org.eclipse.osgi.internal.location.EquinoxLocations#instanceLocation -> org.eclipse.osgi.internal.location.BasicLocation@34db5935
org.eclipse.osgi.internal.framework.EquinoxConfiguration#equinoxLocations -> org.eclipse.osgi.internal.location.EquinoxLocations@621a7d83
org.eclipse.osgi.internal.loader.EquinoxClassLoader#configuration -> org.eclipse.osgi.internal.framework.EquinoxConfiguration@674b2703
org.eclipse.osgi.internal.loader.EquinoxClassLoader -> org.eclipse.osgi.internal.loader.EquinoxClassLoader@409a7dc3[org.eclipse.jdt.ui.tests:3.15.500.v202

. Actual: 0
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.failEquals(Assert.java:187)
at org.junit.Assert.assertNotEquals(Assert.java:201)
at org.eclipse.jdt.ui.leaktest.LeakTestCase.assertInstanceCount(LeakTestCase.java:129)
at org.eclipse.jdt.ui.tests.leaks.JavaLeakTest.internalTestEditorOpen(JavaLeakTest.java:378)
at org.eclipse.jdt.ui.tests.leaks.JavaLeakTest.internalTestEditorClose(JavaLeakTest.java:312)
at org.eclipse.jdt.ui.tests.leaks.JavaLeakTest.testJavaEditorBreadcrumbClose(JavaLeakTest.java:209)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)

```
https://download.eclipse.org/eclipse/downloads/drops4/I20240608-0320/testresults/html/org.eclipse.jdt.ui.tests_ep433I-unit-macM1-java17_macosx.cocoa.aarch64_17.html

**Comment by Wittmaxi** [comment]
Thank you for the report! This is caused by my PR for the Find/Replace overlay. I believe I know how to address this.
