### ISSUE TITLE
BadLocationException when trying to use Refactor - Rename on a java method

### ISSUE THREAD

**Issue by costescuandrei** [eclipse-jdt/eclipse.jdt.ui#146]
I have a class in it's own java file. I try to do ALT+SHIFT+R (or from the context menu refactor - rename) on one of it's public methods. It does not work and I get this exception:

```
org.eclipse.jface.text.BadLocationException
	at org.eclipse.jface.text.link.LinkedPositionGroup.enforceDisjoint(LinkedPositionGroup.java:162)
	at org.eclipse.jface.text.link.LinkedPositionGroup.addPosition(LinkedPositionGroup.java:127)
	at org.eclipse.jdt.internal.ui.refactoring.reorg.RenameLinkedMode.start(RenameLinkedMode.java:304)
	at org.eclipse.jdt.internal.ui.refactoring.actions.RenameJavaElementAction.run(RenameJavaElementAction.java:250)
	at org.eclipse.jdt.internal.ui.refactoring.actions.RenameJavaElementAction.doRun(RenameJavaElementAction.java:190)
	at org.eclipse.jdt.internal.ui.refactoring.actions.RenameJavaElementAction.run(RenameJavaElementAction.java:162)
	at org.eclipse.jdt.ui.actions.RenameAction.run(RenameAction.java:121)
	at org.eclipse.jdt.ui.actions.SelectionDispatchAction.dispatchRun(SelectionDispatchAction.java:278)
	at org.eclipse.jdt.ui.actions.SelectionDispatchAction.run(SelectionDispatchAction.java:252)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:414)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4068)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3645)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.equinox.internal.app.MainApplicationLauncher.run(MainApplicationLauncher.java:36)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
```

```
eclipse.buildId=4.24.0.I20220607-0700
java.version=18.0.1
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.rcp.product -product org.eclipse.wildwebdeveloper.product.branding.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -clean -product org.eclipse.epp.package.rcp.product -product org.eclipse.wildwebdeveloper.product.branding.product -data e:\Workspaces\master
```

**Comment by iloveeclipse** [comment]
@jjohnstn : may be related to https://git.eclipse.org/r/c/jdt/eclipse.jdt.ui/+/70037 changes in `org.eclipse.jdt.internal.ui.refactoring.reorg.RenameLinkedMode.start()`.
Could you please take a look?

**Comment by jjohnstn** [comment]
Ok.

**Comment by jjohnstn** [comment]
@costescuandrei  I don't have access to a Windows box, but it works for me on Linux for Eclipse internal Java classes opened in a 2022-06 "Eclipse for Eclipse Committer's" epp package as well as in the "Eclipse for Enterprise Java and Web Developers" epp package.  Could you provide more information?  What EPP package did you install and did you install any additional products?  If you create a simple Java class with a few public methods, does it still fail for you?  If not, can you provide more details about your particular project and class?

**Comment by costescuandrei** [comment]
Maybe it needs then a special set of java classes. I tried to rename BasicFormController.executePreHideSteps method from https://github.com/Servoy/servoy-client
So https://github.com/Servoy/servoy-client/blob/master/servoy_shared/src/com/servoy/j2db/BasicFormController.java

Yes. I see now that in other classes it works.
Please try to use that git repo. to reproduce it. Let me know if that does not work - I can try to reduce that project to a smaller sample (if needed).

**Comment by jjohnstn** [comment]
Can you please try the latest I-build from: https://download.eclipse.org/eclipse/downloads/ ?

A fix was made to handle a regression in the rename code that among other things caused a BadLocationException to occur under the covers which prevented the rename from occurring after hitting Enter. It also sometimes caused an assertion failure. I have verified that today's I-build contains the fix and I believe it may be the same issue as this one.

The issue recently fixed is: https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/158

The sample test from the issue above is simple.

**Comment by costescuandrei** [comment]
Yes, now it works. Thank you!
