### ISSUE TITLE
`ArrayIndexOutOfBoundsException` in `JUnitLaunchConfigurationDelegate`

### ISSUE THREAD

**Issue by odrotbohm** [eclipse-jdt/eclipse.jdt.ui#1651]
When trying to run JUnit tests from a source folder (right-click `src/test/java`) I get the following exception:

```
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationDelegate.enumerateTypesInPackage(JUnitLaunchConfigurationDelegate.java:543)
	at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationDelegate.collectExecutionArguments(JUnitLaunchConfigurationDelegate.java:473)
	at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationDelegate.getVMRunnerConfiguration(JUnitLaunchConfigurationDelegate.java:182)
	at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationDelegate.launch(JUnitLaunchConfigurationDelegate.java:275)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:805)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:716)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1054)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$1.run(DebugUIPlugin.java:1257)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

```
eclipse.buildId=4.25.0.202409101855
java.version=21.0.4
java.vendor=Eclipse Adoptium
BootLoader constants: OS=macosx, ARCH=aarch64, WS=cocoa, NL=en_US
```

**Comment by iloveeclipse** [comment]
4.25 Eclipse is not supported. Please try with current 4.33 release.

**Comment by odrotbohm** [comment]
It looks like [this commit](https://github.com/eclipse-jdt/eclipse.jdt.ui/commit/87b98a6685cc5a41bea0ffe39496a8b01bc14505) introduced unguarded access to the allegedly present element in a package, whereas the array, of course, could also be empty.

**Comment by odrotbohm** [comment]
> 4.25 Eclipse is not supported. Please try with current 4.33 release.

I'm sorry, that's not the Eclipse version listed here but the one of STS (the Spring-specific tooling). Under the covers, that uses an Eclipse 4.33.0.v20240903-0618 underneath an Eclipse Java Development Tools 3.19.600.v20240903-0240.

**Comment by erik-brangs** [comment]
@odrotbohm Can you share more information about the situation that causes the problem?

IIRC the code should only fail at this location if there are any compilation units without any top-level types.

**Comment by odrotbohm** [comment]
The package structure underneath `src/test/java` looks like this. Some packages indeed solely contain a `package-info.java`.

<img width="330" alt="Screenshot 2024-09-16 at 23 01 35" src="https://github.com/user-attachments/assets/f2ff77e3-6e62-4cf8-b72b-97409fb6ec51">
