### ISSUE TITLE
Setting a breakpoint inside a lamda that contains an object fails

### ISSUE THREAD

**Issue by laeubi** [eclipse-jdt/eclipse.jdt.ui#1681]
Assume the following code

```
package org.eclipse.ui.internal;

import java.util.Optional;
import java.util.function.Consumer;

import org.eclipse.core.databinding.observable.sideeffect.ISideEffectFactory;
import org.eclipse.jface.action.Action;
import org.eclipse.jface.databinding.swt.WidgetSideEffects;
import org.eclipse.swt.widgets.Composite;

public class NoBreakPoint {

	private Context context = new Context();

	public NoBreakPoint(Composite parent) {
		ISideEffectFactory factory = WidgetSideEffects.createFactory(parent);
		factory.create(context::getSample, sample -> new Consumer<Optional<String>>() {

			Optional<String> lastSample = Optional.empty();

			@Override
			public void accept(Optional<String> currentSample) {

				lastSample.ifPresent(System.out::println);
				currentSample.ifPresent(System.out::println);
				lastSample = currentSample;
			}
		});
	}

	private static final class Context {
		public Optional<String> getSample() {
			return Optional.of("An example"); //$NON-NLS-1$
		}
	}

	public void dummy1() {
		new Action() {

			@Override
			public void run() {
				super.run();
			}
		};
	}

}
```

- Now try to set a breakpoint in line 24 (`lastSample.ifPresent(System.out::println);`), it seems noting happens, but the Breakpoint view shows a breakpoint without a line number (in my real world code I get sett a breakpoint far away from the line i double clicked).
- Now double click on that one in the breakpoint view --> nothing happens.
- Now do the same on line 42 (`super.run();`)
- Everything works

Here is a video:

https://github.com/user-attachments/assets/112aeb33-e76d-419d-82de-975e2776e9c4

```
Eclipse SDK

Version: 2024-12 (4.34)
Build id: I20240921-1800
```

**Comment by nettozahler** [comment]
Question: what is the best way to set up a proper example project having `org.eclipse.core.*`, `org.eclipse.jface.*`and `org.eclipse.swt.*` as dependencies so the above code compiles? Add some Eclipse projects to the classpath?

Anyhow - I did some mocking to make it compile and could reproduce it. I get the following error in the log:

```
org.eclipse.jface.text.BadLocationException: -1
	at org.eclipse.jface.text.TreeLineTracker.getLineInformation(TreeLineTracker.java:1153)
	at org.eclipse.jface.text.AbstractLineTracker.getLineInformation(AbstractLineTracker.java:228)
	at org.eclipse.jface.text.AbstractDocument.getLineInformation(AbstractDocument.java:873)
	at org.eclipse.core.internal.filebuffers.SynchronizableDocument.getLineInformation(SynchronizableDocument.java:290)
	at org.eclipse.jdt.internal.debug.ui.actions.ToggleBreakpointAdapter.doLineBreakpointToggle(ToggleBreakpointAdapter.java:529)
	at org.eclipse.jdt.internal.debug.ui.actions.ToggleBreakpointAdapter$1.run(ToggleBreakpointAdapter.java:213)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

**Comment by laeubi** [comment]
I extracted it from a real use-case, but usually a recent Eclipse as target platform should be enough, probably only the structure needs to be preserved, for example `Action` --> `Runnable`, `Composite` -> `Object` and so on...
