### ISSUE TITLE
VisitorTest failing since I20241015-1820

### ISSUE THREAD

**Issue by noopur2507** [eclipse-jdt/eclipse.jdt.ui#1722]
org.eclipse.jdt.internal.common.VisitorTest is failing in I-builds since I20241015-1820.

https://download.eclipse.org/eclipse/downloads/drops4/I20241016-2000/testresults/html/org.eclipse.jdt.ui.tests_ep434I-unit-macM1-java17_macosx.cocoa.aarch64_17.html

```
VisitorTest

Missing system library

java.lang.IllegalStateException: Missing system library
at org.eclipse.jdt.core.dom.ASTParser.checkForSystemLibrary(ASTParser.java:311)
at org.eclipse.jdt.core.dom.ASTParser.getClasspath(ASTParser.java:272)
at org.eclipse.jdt.core.dom.ASTParser.internalCreateASTCached(ASTParser.java:1299)
at org.eclipse.jdt.core.dom.ASTParser.lambda$1(ASTParser.java:1178)
at org.eclipse.jdt.internal.core.JavaModelManager.cacheZipFiles(JavaModelManager.java:5692)
at org.eclipse.jdt.core.dom.ASTParser.internalCreateAST(ASTParser.java:1178)
at org.eclipse.jdt.core.dom.ASTParser.createAST(ASTParser.java:918)
at org.eclipse.jdt.internal.common.VisitorTest.init(VisitorTest.java:81)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

**Comment by stephan-herrmann** [comment]
Thanks, @noopur2507 , I'll take a look.
