### ISSUE TITLE
12 Progress monitor test failures since I20241204-1800

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.ui#1833]
for example:
```
Progress monitor assertion failed

org.eclipse.core.tests.harness.FussyProgressMonitor$FussyProgressAssertionFailed: Progress monitor assertion failed
at org.eclipse.core.tests.harness.FussyProgressMonitor.processFailedAssertion(FussyProgressMonitor.java:83)
at org.eclipse.core.tests.harness.FussyProgressMonitor.wrapAssertion(FussyProgressMonitor.java:73)
at org.eclipse.core.tests.harness.FussyProgressMonitor.assertUsedUp(FussyProgressMonitor.java:96)
at org.eclipse.jdt.ui.tests.quickfix.ChangeNonStaticToStaticTest.assertRefactoringResultAsExpected(ChangeNonStaticToStaticTest.java:107)
at org.eclipse.jdt.ui.tests.quickfix.ChangeNonStaticToStaticTest.testNonStaticAccessTest01(ChangeNonStaticToStaticTest.java:150)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
Caused by: java.lang.AssertionError: [work done]
Expecting actual:
500L
to be greater than or equal to:
1000L

at org.eclipse.core.tests.harness.FussyProgressMonitor.lambda$1(FussyProgressMonitor.java:96)
at org.eclipse.core.tests.harness.FussyProgressMonitor.wrapAssertion(FussyProgressMonitor.java:71)
... 4 more
```
https://download.eclipse.org/eclipse/downloads/drops4/I20241204-1800/testResults.php

**Comment by jukzi** [comment]
cc @vogella since you are working on Progress monitor

**Comment by jukzi** [comment]
caused by https://github.com/eclipse-platform/eclipse.platform.ui/pull/2573 @vogella, please stop removing subMon.done() blindly

**Comment by vogella** [comment]
To fulfil the test assumption in  JDT, Refactoring  needs to consume all ticks, which it so far did not explicitly but implicitly via the done() call. Revert is fine for me for now I might adjust Refactoring at a later point in time. AFAICS functional-wise nothing has changed with the removal of done(), it only affects the test check, as the top-level monitor done() call will also consume the ticks so this failure should be "test assumption failure" only.

**Comment by vogella** [comment]
Revert available from @jukzi https://github.com/eclipse-platform/eclipse.platform.ui/pull/2586
