### ISSUE TITLE
Random failing TypeRulesTest.testCanCast

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.ui#1834]
First observed on windows:
https://download.eclipse.org/eclipse/downloads/drops4/I20241204-1800/testresults/html/org.eclipse.jdt.ui.tests_ep435I-unit-win32-x86_64-java17_win32.win32.x86_64_17.html
```
java.lang.AssertionError: boolean x= (boolean) bool
char x= (char) c
byte x= (byte) c
short x= (short) c
int x= (int) c
long x= (long) c
float x= (float) c
double x= (double) c
char x= (char) b
byte x= (byte) b
short x= (short) b
int x= (int) b
long x= (long) b
float x= (float) b
double x= (double) b
char x= (char) s
byte x= (byte) s
short x= (short) s
int x= (int) s
long x= (long) s
float x= (float) s
double x= (double) s
char x= (char) i
byte x= (byte) i
short x= (short) i
int x= (int) i
long x= (long) i
float x= (float) i
double x= (double) i
char x= (char) l
byte x= (byte) l
short x= (short) l
int x= (int) l
long x= (long) l
float x= (float) l
double x= (double) l
char x= (char) f
byte x= (byte) f
short x= (short) f
int x= (int) f
long x= (long) f
float x= (float) f
double x= (double) f
char x= (char) d
byte x= (byte) d
short x= (short) d
int x= (int) d
long x= (long) d
float x= (float) d
double x= (double) d
java.lang.Boolean x= (java.lang.Boolean) bool_class
java.lang.Object x= (java.lang.Object) bool_class
java.io.Serializable x= (java.io.Serializable) bool_class
java.lang.Character x= (java.lang.Character) c_class
java.lang.Object x= (java.lang.Object) c_class
java.io.Serializable x= (java.io.Serializable) c_class
java.lang.Byte x= (java.lang.Byte) b_class
java.lang.Object x= (java.lang.Object) b_class
java.io.Serializable x= (java.io.Serializable) b_class
java.lang.Short x= (java.lang.Short) s_class
java.lang.Object x= (java.lang.Object) s_class
java.io.Serializable x= (java.io.Serializable) s_class
java.lang.Integer x= (java.lang.Integer) i_class
java.lang.Object x= (java.lang.Object) i_class
java.io.Serializable x= (java.io.Serializable) i_class
java.lang.Long x= (java.lang.Long) l_class
java.lang.Object x= (java.lang.Object) l_class
java.io.Serializable x= (java.io.Serializable) l_class
java.lang.Float x= (java.lang.Float) f_class
java.lang.Object x= (java.lang.Object) f_class
java.io.Serializable x= (java.io.Serializable) f_class
java.lang.Double x= (java.lang.Double) d_class
java.lang.Object x= (java.lang.Object) d_class
java.io.Serializable x= (java.io.Serializable) d_class
java.lang.Boolean x= (java.lang.Boolean) object
java.lang.Character x= (java.lang.Character) object
java.lang.Byte x= (java.lang.Byte) object
java.lang.Short x= (java.lang.Short) object
java.lang.Integer x= (java.lang.Integer) object
java.lang.Long x= (java.lang.Long) object
java.lang.Float x= (java.lang.Float) object
java.lang.Double x= (java.lang.Double) object
java.lang.Object x= (java.lang.Object) object
java.net.Socket x= (java.net.Socket) object
java.lang.Cloneable x= (java.lang.Cloneable) object
java.io.Serializable x= (java.io.Serializable) object
java.lang.Object[] x= (java.lang.Object[]) object
int[] x= (int[]) object
long[] x= (long[]) object
java.util.Vector[] x= (java.util.Vector[]) object
java.net.Socket[] x= (java.net.Socket[]) object
java.util.Collection[] x= (java.util.Collection[]) object
java.lang.Object[][] x= (java.lang.Object[][]) object
java.util.Collection[][] x= (java.util.Collection[][]) object
java.util.Vector[][] x= (java.util.Vector[][]) object
java.net.Socket[][] x= (java.net.Socket[][]) object
java.util.Vector x= (java.util.Vector) vector
java.util.Collection x= (java.util.Collection) vector
java.lang.Object x= (java.lang.Object) socket
java.net.Socket x= (java.net.Socket) socket
java.lang.Cloneable x= (java.lang.Cloneable) socket
java.io.Serializable x= (java.io.Serializable) socket
java.lang.Object x= (java.lang.Object) cloneable
java.net.Socket x= (java.net.Socket) cloneable
java.lang.Cloneable x= (java.lang.Cloneable) cloneable
java.io.Serializable x= (java.io.Serializable) cloneable
java.lang.Object[] x= (java.lang.Object[]) cloneable
int[] x= (int[]) cloneable
long[] x= (long[]) cloneable
java.util.Vector[] x= (java.util.Vector[]) cloneable
java.net.Socket[] x= (java.net.Socket[]) cloneable
java.util.Collection[] x= (java.util.Collection[]) cloneable
java.lang.Object[][] x= (java.lang.Object[][]) cloneable
java.util.Collection[][] x= (java.util.Collection[][]) cloneable
java.util.Vector[][] x= (java.util.Vector[][]) cloneable
java.net.Socket[][] x= (java.net.Socket[][]) cloneable
java.util.Vector x= (java.util.Vector) collection
java.util.Collection x= (java.util.Collection) collection
java.lang.Boolean x= (java.lang.Boolean) serializable
java.lang.Character x= (java.lang.Character) serializable
java.lang.Byte x= (java.lang.Byte) serializable
java.lang.Short x= (java.lang.Short) serializable
java.lang.Integer x= (java.lang.Integer) serializable
java.lang.Long x= (java.lang.Long) serializable
java.lang.Float x= (java.lang.Float) serializable
java.lang.Double x= (java.lang.Double) serializable
java.lang.Object x= (java.lang.Object) serializable
java.net.Socket x= (java.net.Socket) serializable
java.lang.Cloneable x= (java.lang.Cloneable) serializable
java.io.Serializable x= (java.io.Serializable) serializable
java.lang.Object[] x= (java.lang.Object[]) serializable
int[] x= (int[]) serializable
long[] x= (long[]) serializable
java.util.Vector[] x= (java.util.Vector[]) serializable
java.net.Socket[] x= (java.net.Socket[]) serializable
java.util.Collection[] x= (java.util.Collection[]) serializable
java.lang.Object[][] x= (java.lang.Object[][]) serializable
java.util.Collection[][] x= (java.util.Collection[][]) serializable
java.util.Vector[][] x= (java.util.Vector[][]) serializable
java.net.Socket[][] x= (java.net.Socket[][]) serializable
java.lang.Object x= (java.lang.Object) objectArr
java.lang.Cloneable x= (java.lang.Cloneable) objectArr
java.io.Serializable x= (java.io.Serializable) objectArr
java.lang.Object[] x= (java.lang.Object[]) objectArr
java.util.Vector[] x= (java.util.Vector[]) objectArr
java.net.Socket[] x= (java.net.Socket[]) objectArr
java.util.Collection[] x= (java.util.Collection[]) objectArr
java.lang.Object[][] x= (java.lang.Object[][]) objectArr
java.util.Collection[][] x= (java.util.Collection[][]) objectArr
java.util.Vector[][] x= (java.util.Vector[][]) objectArr
java.net.Socket[][] x= (java.net.Socket[][]) objectArr
java.lang.Object x= (java.lang.Object) int_arr
java.lang.Cloneable x= (java.lang.Cloneable) int_arr
java.io.Serializable x= (java.io.Serializable) int_arr
int[] x= (int[]) int_arr
java.lang.Object x= (java.lang.Object) long_arr
java.lang.Cloneable x= (java.lang.Cloneable) long_arr
java.io.Serializable x= (java.io.Serializable) long_arr
long[] x= (long[]) long_arr
java.lang.Object x= (java.lang.Object) vector_arr
java.lang.Cloneable x= (java.lang.Cloneable) vector_arr
java.io.Serializable x= (java.io.Serializable) vector_arr
java.lang.Object[] x= (java.lang.Object[]) vector_arr
java.util.Vector[] x= (java.util.Vector[]) vector_arr
java.util.Collection[] x= (java.util.Collection[]) vector_arr
java.lang.Object x= (java.lang.Object) socket_arr
java.lang.Cloneable x= (java.lang.Cloneable) socket_arr
java.io.Serializable x= (java.io.Serializable) socket_arr
java.lang.Object[] x= (java.lang.Object[]) socket_arr
java.net.Socket[] x= (java.net.Socket[]) socket_arr
java.util.Collection[] x= (java.util.Collection[]) socket_arr
java.lang.Object x= (java.lang.Object) collection_arr
java.lang.Cloneable x= (java.lang.Cloneable) collection_arr
java.io.Serializable x= (java.io.Serializable) collection_arr
java.lang.Object[] x= (java.lang.Object[]) collection_arr
java.util.Vector[] x= (java.util.Vector[]) collection_arr
java.net.Socket[] x= (java.net.Socket[]) collection_arr
java.util.Collection[] x= (java.util.Collection[]) collection_arr
java.lang.Object x= (java.lang.Object) objectArrArr
java.lang.Cloneable x= (java.lang.Cloneable) objectArrArr
java.io.Serializable x= (java.io.Serializable) objectArrArr
java.lang.Object[] x= (java.lang.Object[]) objectArrArr
java.lang.Object[][] x= (java.lang.Object[][]) objectArrArr
java.util.Collection[][] x= (java.util.Collection[][]) objectArrArr
java.util.Vector[][] x= (java.util.Vector[][]) objectArrArr
java.net.Socket[][] x= (java.net.Socket[][]) objectArrArr
java.lang.Object x= (java.lang.Object) collection_arrarr
java.lang.Cloneable x= (java.lang.Cloneable) collection_arrarr
java.io.Serializable x= (java.io.Serializable) collection_arrarr
java.lang.Object[] x= (java.lang.Object[]) collection_arrarr
java.lang.Object[][] x= (java.lang.Object[][]) collection_arrarr
java.util.Collection[][] x= (java.util.Collection[][]) collection_arrarr
java.util.Vector[][] x= (java.util.Vector[][]) collection_arrarr
java.net.Socket[][] x= (java.net.Socket[][]) collection_arrarr
java.lang.Object x= (java.lang.Object) vector_arrarr
java.lang.Cloneable x= (java.lang.Cloneable) vector_arrarr
java.io.Serializable x= (java.io.Serializable) vector_arrarr
java.lang.Object[] x= (java.lang.Object[]) vector_arrarr
java.lang.Object[][] x= (java.lang.Object[][]) vector_arrarr
java.util.Collection[][] x= (java.util.Collection[][]) vector_arrarr
java.util.Vector[][] x= (java.util.Vector[][]) vector_arrarr
java.lang.Object x= (java.lang.Object) socket_arrarr
java.lang.Cloneable x= (java.lang.Cloneable) socket_arrarr
java.io.Serializable x= (java.io.Serializable) socket_arrarr
java.lang.Object[] x= (java.lang.Object[]) socket_arrarr
java.lang.Object[][] x= (java.lang.Object[][]) socket_arrarr
java.util.Collection[][] x= (java.util.Collection[][]) socket_arrarr
java.net.Socket[][] x= (java.net.Socket[][]) socket_arrarr
expected:<0> but was:<9315>
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.failNotEquals(Assert.java:835)
at org.junit.Assert.assertEquals(Assert.java:647)
at org.eclipse.jdt.ui.tests.core.TypeRulesTest.testCanCast(TypeRulesTest.java:330)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

**Comment by jukzi** [comment]
can not locally reproduce
