### ISSUE TITLE
ClassCastException AsyncCompletionProposalPopup in ContinuousTypingCompletionTest

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.ui#1835]
ContinuousTypingCompletionTest.testContinousTypingSelectsTopProposal failed in
https://download.eclipse.org/eclipse/downloads/drops4/I20241204-1800/testresults/html/org.eclipse.jdt.text.tests_ep435I-unit-macosx-x86_64-java17_macosx.cocoa.x86_64_17.html
```
java.lang.ClassCastException: class org.eclipse.jface.text.contentassist.AsyncCompletionProposalPopup$ComputingProposal cannot be cast to class org.eclipse.jdt.internal.ui.text.java.AbstractJavaCompletionProposal (org.eclipse.jface.text.contentassist.AsyncCompletionProposalPopup$ComputingProposal is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @274d1785; org.eclipse.jdt.internal.ui.text.java.AbstractJavaCompletionProposal is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @bad6718)
at org.eclipse.jdt.text.tests.contentassist.ContinuousTypingCompletionTest$CompletionSelectionTracker.getSelectedProposal(ContinuousTypingCompletionTest.java:60)
at org.eclipse.jdt.text.tests.contentassist.ContinuousTypingCompletionTest.testContinousTypingSelectsTopProposal(ContinuousTypingCompletionTest.java:87)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```
locally reproducable on win
![image](https://github.com/user-attachments/assets/e9bfd6a8-c186-4584-9e73-29aa0d1f52b2)

cc @mickaelistria @testforstephen because you are working on classloader issues - any idea?

**Comment by mickaelistria** [comment]
This is a regular classCastException, not a classloader issue. ComputingProposal is *not* an instance of AbstractJavaCompletionProposal. The question is what has changed: is it that ComputingProposal is now returned (ie completion in JDT being async?) or that AbstractJavaCompletionProposal is freshly expected?

**Comment by jukzi** [comment]
I could not find any recent change that made the test work again.

**Comment by jukzi** [comment]
it's a race condition. Probably something got faster or slower. Found a way to fix it by appropriate wait.
