### ISSUE TITLE
SmokeViewsTest.testOpenSourceView fails since I20241206-1800

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.ui#1843]
All OS
```
java.lang.AssertionError: Error happened on opening view org.eclipse.jdt.ui.SourceView
at org.junit.Assert.fail(Assert.java:89)
at org.eclipse.jdt.ui.tests.views.SmokeViewsTest.smokeTest(SmokeViewsTest.java:143)
at org.eclipse.jdt.ui.tests.views.SmokeViewsTest.testOpenSourceView(SmokeViewsTest.java:133)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```
for example https://download.eclipse.org/eclipse/downloads/drops4/I20241206-1800/testresults/html/org.eclipse.jdt.ui.tests_ep435I-unit-macosx-x86_64-java17_macosx.cocoa.x86_64_17.html

locally reproducible, logs NPE:
```
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at java.base/java.util.Arrays$ArrayList.<init>(Arrays.java:4238)
	at java.base/java.util.Arrays.asList(Arrays.java:4223)
	at org.eclipse.jface.text.source.SourceViewer.configure(SourceViewer.java:550)
	at org.eclipse.jdt.internal.ui.javaeditor.JavaSourceViewer.configure(JavaSourceViewer.java:224)
	at org.eclipse.jdt.internal.ui.infoviews.SourceView.internalCreatePartControl(SourceView.java:199)
	at org.eclipse.jdt.internal.ui.infoviews.AbstractInfoView.createPartControl(AbstractInfoView.java:235)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPartControl(CompatibilityPart.java:158)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityView.createPartControl(CompatibilityView.java:155)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:365)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:977)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:939)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalInject(InjectorImpl.java:139)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:386)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:312)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:203)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.createFromBundle(ReflectionContributionFactory.java:90)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.doCreate(ReflectionContributionFactory.java:59)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.create(ReflectionContributionFactory.java:42)
	at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.createWidget(ContributedPartRenderer.java:134)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:991)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:658)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$1.run(PartRenderingEngine.java:543)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:527)
	at org.eclipse.e4.ui.workbench.renderers.swt.ElementReferenceRenderer.createWidget(ElementReferenceRenderer.java:73)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:991)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:658)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:762)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:727)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:711)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.lambda$0(PartServiceImpl.java:110)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.lambda$0(UIEventHandler.java:38)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:183)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4941)
	at org.eclipse.e4.ui.workbench.swt.DisplayUISynchronize.syncExec(DisplayUISynchronize.java:34)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.handleEvent(UIEventHandler.java:38)
	at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:206)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:201)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:131)
	at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:73)
	at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:44)
	at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:55)
	at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:60)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:424)
	at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElementGen(ElementContainerImpl.java:168)
	at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElement(ElementContainerImpl.java:187)
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.showElementInWindow(ModelServiceImpl.java:654)
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.bringToTop(ModelServiceImpl.java:618)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.delegateBringToTop(PartServiceImpl.java:796)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:764)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:686)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:681)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.showPart(PartServiceImpl.java:1262)
	at org.eclipse.ui.internal.WorkbenchPage.showPart(WorkbenchPage.java:1245)
	at org.eclipse.ui.internal.WorkbenchPage.busyShowView(WorkbenchPage.java:1233)
	at org.eclipse.ui.internal.WorkbenchPage.lambda$13(WorkbenchPage.java:4243)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:67)
	at org.eclipse.ui.internal.WorkbenchPage.showView(WorkbenchPage.java:4241)
	at org.eclipse.ui.internal.WorkbenchPage.showView(WorkbenchPage.java:4225)
	at org.eclipse.jdt.ui.tests.views.SmokeViewsTest.smokeTest(SmokeViewsTest.java:138)
	at org.eclipse.jdt.ui.tests.views.SmokeViewsTest.testOpenSourceView(SmokeViewsTest.java:133)
```

Caused by https://github.com/eclipse-platform/eclipse.platform.ui/pull/2051 @mickaelistria, @lathapatil
Please always check next CI build after submitting anything to find regressions in other related plugins.

**Comment by iloveeclipse** [comment]
To reproduce in the IDE, just try to open "Declaration" view.

**Comment by jukzi** [comment]
![image](https://github.com/user-attachments/assets/8f8043f0-a7ed-432a-a7cf-152ea3c18b68)

**Comment by vogella** [comment]
Also broken:  Source -> Clean-up and select Configure I get a NPE

![image](https://github.com/user-attachments/assets/939b2fd2-4a61-4bb6-9b7b-c5a3961433c4)

````
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at java.base/java.util.Arrays$ArrayList.<init>(Arrays.java:4238)
	at java.base/java.util.Arrays.asList(Arrays.java:4223)
	at org.eclipse.jface.text.source.SourceViewer.configure(SourceViewer.java:550)
	at org.eclipse.jdt.internal.ui.javaeditor.JavaSourceViewer.configure(JavaSourceViewer.java:224)
	at org.eclipse.jdt.internal.ui.preferences.formatter.JavaPreview.<init>(JavaPreview.java:135)
	at org.eclipse.jdt.internal.ui.preferences.cleanup.CleanUpPreview.<init>(CleanUpPreview.java:50)
	at org.eclipse.jdt.internal.ui.preferences.cleanup.CleanUpTabPage.doCreateJavaPreview(CleanUpTabPage.java:100)
	at org.eclipse.jdt.internal.ui.preferences.cleanup.CodeFormatingTabPage.doCreateJavaPreview(CodeFormatingTabPage.java:67)
	at org.eclipse.jdt.internal.ui.preferences.formatter.ModifyDialogTabPage.doCreatePreviewPane(ModifyDialogTabPage.java:962)
	at org.eclipse.jdt.internal.ui.preferences.formatter.ModifyDialogTabPage.createContents(ModifyDialogTabPage.java:912)
	at org.eclipse.jdt.internal.ui.fix.CleanUpSelectionDialog.addTabPage(CleanUpSelectionDialog.java:253)
	at org.eclipse.jdt.internal.ui.fix.CleanUpSelectionDialog.createDialogArea(CleanUpSelectionDialog.java:178)
	at org.eclipse.jface.dialogs.Dialog.createContents(Dialog.java:766)
	at org.eclipse.jface.window.Window.create(Window.java:431)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1092)
	at org.eclipse.jface.dialogs.StatusDialog.create(StatusDialog.java:130)
	at org.eclipse.jdt.internal.ui.fix.CleanUpSelectionDialog.create(CleanUpSelectionDialog.java:129)
	at org.eclipse.jface.window.Window.open(Window.java:788)
	at org.eclipse.jdt.internal.ui.fix.CleanUpRefactoringWizard$CleanUpConfigurationPage$2.widgetSelected(CleanUpRefactoringWizard.java:364)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:286)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:91)

````

**Comment by mickaelistria** [comment]
https://github.com/eclipse-platform/eclipse.platform.ui/pull/2612#issuecomment-2531882618 is supposed to fix this. Can you please verify ?
