### ISSUE TITLE
Enable LeakTestSuite in org.eclipse.jdt.ui.tests pom.xml file 

### ISSUE THREAD

**Issue by ktatavarthi** [eclipse-jdt/eclipse.jdt.ui#2]
LeakTestSuite in org.eclipse.jdt.ui.tests pom.xml file has been disabled as these tests are failing in the jenkins github job

https://ci.eclipse.org/jdt/job/eclipse.jdt.ui-github/job/PR-1/10/

This issue is to trak the enablement of LeakTestSuite in org.eclipse.jdt.ui.tests pom.xml file once a fix is provided so these tests pass in the job https://ci.eclipse.org/jdt/job/eclipse.jdt.ui-github

**Comment by ktatavarthi** [comment]
@mickaelistria Can you please provide your inputs in this regard?

**Comment by ktatavarthi** [comment]
This bug has been created as a follow up to https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1#issuecomment-1093684675

**Comment by mickaelistria** [comment]
Sorry, I don't know (or remember) anything about this test suite. Did it just start to fail after migration to GitHub? Which particular test?

**Comment by ktatavarthi** [comment]
All Leak tests part of this test suite fail : 23 of them

**Comment by mickaelistria** [comment]
This should now be fixed in latest Tycho snapshots. Please retry.

**Comment by stephan-herrmann** [comment]
I can successfully run these tests within the IDE (by manually supplying a bunch of arguments to the uitestapplication), but it looks like JDK 17 is the last that allows these tests to run:

When I run those tests on 18+, each test fails with:
```
java.lang.IllegalArgumentException: Can not get final java.lang.Class field java.lang.Class.componentType on java.lang.Class
        at java.base/jdk.internal.reflect.MethodHandleFieldAccessorImpl.newGetIllegalArgumentException(MethodHandleFieldAccessorImpl.java:86)
        at java.base/jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.get(MethodHandleObjectFieldAccessorImpl.java:61)
        at java.base/java.lang.reflect.Field.get(Field.java:428)
        at org.eclipse.jdt.ui.leaktest.reftracker.ReferenceTracker.followFieldReference(ReferenceTracker.java:80)
        at org.eclipse.jdt.ui.leaktest.reftracker.ReferenceTracker.visit(ReferenceTracker.java:144)
        at org.eclipse.jdt.ui.leaktest.reftracker.ReferenceTracker.start(ReferenceTracker.java:168)
        at org.eclipse.jdt.ui.leaktest.LeakTestCase.collect(LeakTestCase.java:58)
        at org.eclipse.jdt.ui.leaktest.LeakTestCase.assertInstanceCount(LeakTestCase.java:123)
        at org.eclipse.jdt.ui.tests.leaks.JavaLeakTest.internalTestEditorOpen(JavaLeakTest.java:378)
        at org.eclipse.jdt.ui.tests.leaks.JavaLeakTest.internalTestEditorClose(JavaLeakTest.java:312)
        at org.eclipse.jdt.ui.tests.leaks.JavaLeakTest.internalTestEditorClose(JavaLeakTest.java:308)
        at org.eclipse.jdt.ui.tests.leaks.JavaLeakTest.testTextEditorClose(JavaLeakTest.java:91)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
```

Contrary to my first guess it is not a permission issue: hidden in that IllegalArgumentException is `java.lang.ClassCastException: Cannot cast [I to java.lang.Class`

Weird enough I see the debugger showing field `componentType` as an empty *array*, so perhaps it has a value of type  `[I` indeed, despite the declaration as `Class<?>`??

I first saw this for class `org.osgi.service.log.FormatterLogger`, but look, after executing this:
```
org.osgi.service.log.FormatterLogger.class.getComponentType()
```
the former int-array is gone, now the field is `null`, and can be accessed via reflection OK.  But the same then happens for other classes. Spooky, huh? Is that some internal VM magic, that abuses the field in violation of its declaration?

I could think of a bug in the debugger, but then it's the same cause that lets the tests fail in real life.

Well, seeing that `org.eclipse.jdt.ui.leaktest.reftracker.ReferenceTracker.followFieldReference(ReferencedObject, Object, Field)` already excludes fields from packages `jdk` and `sun`, perhaps it should also exclude fields of `java.lang.Class`.
