### ISSUE TITLE
Refactor rename reports shadowing when there is none

### ISSUE THREAD

**Issue by trancexpress** [eclipse-jdt/eclipse.jdt.ui#201]
**To reproduce:**

1. Import projects from: [RefactorRenameShadowingBug.zip](https://github.com/eclipse-jdt/eclipse.jdt.ui/files/9268291/RefactorRenameShadowingBug.zip)
2. Open type ```test1.impl.ITes`t``.
3. Refactor rename ```foo()``` to ```foo1()```.
4. Observe reported shadowing problems:

![RefactorRenameShadowingBug](https://user-images.githubusercontent.com/24752155/183072217-2859c609-534e-4da3-b54a-eed65219d864.png)

There is no shadowing though, the rename is fine.

**Cause:**

Looks like JDT UI "thinks" there are no search matches for the new method in the mentioned files, after the rename. So it reports shadowing (as it thinks the rename did nothing).

This is the case due to the order of elements passed to: ```RenameMethodProcessor.batchFindNewOccurrences()``` (and in particular, delegated to ```RefactoringScopeFactory.create(IMember[]))```. ```test2.Foo``` seems to be found first by ```RippleMethodFinder2.getRelatedMethods()``` and so only its project is used for the search. I.e. the scope is created with only the project ```Test2``` and so the search misses some occurrences. The refactor rename then thinks those missed occurrences are shadowing, instead of subject to the rename.

The problem is created with this stack trace:

```
"ModalContext" #199 prio=6 os_prio=0 cpu=45.89ms elapsed=16.76s tid=0x00007ffff3240000 nid=0x3dce at breakpoint [0x00007fff29cf4000]
   java.lang.Thread.State: RUNNABLE
        at org.eclipse.jdt.internal.corext.refactoring.rename.RenameAnalyzeUtil.addShadowsError(RenameAnalyzeUtil.java:387)
        at org.eclipse.jdt.internal.corext.refactoring.rename.RenameAnalyzeUtil.analyzeRenameChanges2(RenameAnalyzeUtil.java:277)
        at org.eclipse.jdt.internal.corext.refactoring.rename.RenameMethodProcessor.analyzeRenameChanges(RenameMethodProcessor.java:572)
        at org.eclipse.jdt.internal.corext.refactoring.rename.RenameMethodProcessor.doCheckFinalConditions(RenameMethodProcessor.java:412)
        at org.eclipse.jdt.internal.corext.refactoring.rename.RenameVirtualMethodProcessor.doCheckFinalConditions(RenameVirtualMethodProcessor.java:148)
        at org.eclipse.jdt.internal.corext.refactoring.rename.JavaRenameProcessor.checkFinalConditions(JavaRenameProcessor.java:51)
        at org.eclipse.ltk.core.refactoring.participants.ProcessorBasedRefactoring.checkFinalConditions(ProcessorBasedRefactoring.java:226)
        at org.eclipse.ltk.core.refactoring.Refactoring.checkAllConditions(Refactoring.java:165)
        at org.eclipse.jdt.internal.ui.refactoring.RefactoringExecutionHelper$Operation.run(RefactoringExecutionHelper.java:84)
        at org.eclipse.jdt.internal.core.BatchOperation.executeOperation(BatchOperation.java:41)
        at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:740)
        at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2380)
        at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2405)
        at org.eclipse.jdt.core.JavaCore.run(JavaCore.java:5929)
        at org.eclipse.jdt.internal.ui.actions.WorkbenchRunnableAdapter.run(WorkbenchRunnableAdapter.java:108)
        at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**Comment by jjohnstn** [comment]
Verified for 4.25 M3 using I20220817-0600 build
