### ISSUE TITLE
Java Code Assist: javaCompletionProposal throws runtime exception

### ISSUE THREAD

**Issue by nimo23** [eclipse-jdt/eclipse.jdt.ui#230]
Within the java editor, I get this error  when using **eclipse code assist**:

![Screenshot at Aug 23 16-08-12](https://user-images.githubusercontent.com/3045549/186180727-872ff036-800f-4f41-ad11-72c99cbb0ed1.png)

```
The 'org.eclipse.jdt.ui.org.eclipse.jdt.ui.javaCompletionProposalComputer.chain' proposal computer from the 'org.eclipse.jdt.ui' plug-in did not complete normally. The extension has thrown a runtime exception.

java.lang.NumberFormatException: Cannot parse null string
	at java.base/java.lang.Integer.parseInt(Integer.java:630)
	at java.base/java.lang.Integer.parseInt(Integer.java:786)
	at org.eclipse.jdt.internal.ui.text.java.ChainCompletionProposalComputer.executeCallChainSearch(ChainCompletionProposalComputer.java:152)
	at org.eclipse.jdt.internal.ui.text.java.ChainCompletionProposalComputer.computeCompletionProposals(ChainCompletionProposalComputer.java:77)
	at org.eclipse.jdt.internal.ui.text.java.CompletionProposalComputerDescriptor.computeCompletionProposals(CompletionProposalComputerDescriptor.java:348)
	at org.eclipse.jdt.internal.ui.text.java.CompletionProposalCategory.computeCompletionProposals(CompletionProposalCategory.java:340)
	at org.eclipse.jdt.internal.ui.text.java.ContentAssistProcessor.collectProposals(ContentAssistProcessor.java:333)
	at org.eclipse.jdt.internal.ui.text.java.ContentAssistProcessor.computeCompletionProposals(ContentAssistProcessor.java:289)
	at org.eclipse.jface.text.contentassist.ContentAssistant$2.lambda$0(ContentAssistant.java:2048)
	at java.base/java.util.Collections$SingletonSet.forEach(Collections.java:4905)
	at org.eclipse.jface.text.contentassist.ContentAssistant$2.run(ContentAssistant.java:2047)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jface.text.contentassist.ContentAssistant.computeCompletionProposals(ContentAssistant.java:2044)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.computeProposals(CompletionProposalPopup.java:577)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.lambda$0(CompletionProposalPopup.java:507)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.showProposals(CompletionProposalPopup.java:502)
	at org.eclipse.jface.text.contentassist.ContentAssistant$AutoAssistListener.lambda$0(ContentAssistant.java:399)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4345)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3968)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
```

Using:
- Eclipse IDE Version: 2022-06 (4.24.0)
- JDK 17

I can disable "Chain Template Proposals" in Preference->Content-Assist->Advanced to not have an error, but then I don't have "Chain Template Proposals" anymore.

Btw, the "**Eclipse Code Recommenders**" did also throw such an exception. I disabled it to have no error. But after that, it complains about "Chain Template Proposals".

**Comment by kaziabidazad** [comment]
Were you able to find a solution to this? I am facing the same with eclipse 2023.12
eclipse.buildId=4.30.0.20231201-1200
java.version=17.0.9
java.vendor=Eclipse Adoptium

**Comment by jukzi** [comment]
@rgrunber code was added with 01d2391c4f95df250b36675d9660720c457233ac - maybe executeCallChainSearch() can just return empty list if preferences are not found, or any good use any good default value when preferences null?

**Comment by rgrunber** [comment]
We can definitely fix this with an easy workaround. It looks like we're trying to call `Integer.parseInt(..)` on `null` which is wrong. I'm more interested in how this is happening. The value comes from https://github.com/eclipse-jdt/eclipse.jdt.ui/blob/6a8301e7125a7b1a3e93294ea9e8601b006c6477/org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/core/manipulation/JavaManipulation.java#L108-L120

The only way that returns `null` is if the default scope isn't set but we do set it at :

https://github.com/eclipse-jdt/eclipse.jdt.ui/blob/6a8301e7125a7b1a3e93294ea9e8601b006c6477/org.eclipse.jdt.ui/ui/org/eclipse/jdt/ui/PreferenceConstants.java#L4148-L4152 .

If you look up the chain, `store` is just a `ScopedPreferenceStore` where `setDefault(...)` uses the `DefaultScope.INSTANCE`. `fgPreferenceNodeId` also can't be `null` because that would throw an `IllegalArgumentException` earlier.

**Comment by jukzi** [comment]
i think that NPE should still be fixed

**Comment by jukzi** [comment]
> **Update:** Ok, I think I have some idea. This initialization all comes from the core runtime, at :

@rgrunber can you please provide a fix or at least a null check to avoid NPE?
