### ISSUE TITLE
HierarchicalASTVisitorTest fails

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.ui#231]
Regression from https://github.com/eclipse-jdt/eclipse.jdt.core/pull/328 

https://download.eclipse.org/eclipse/downloads/drops4/I20220823-1800/testresults/html/org.eclipse.jdt.ui.tests_ep425I-unit-cen64-gtk3-java18_linux.gtk.x86_64_18.html

HierarchicalASTVisitor must be updated to reflect a change in the ASTNode hierarchy. No method visit(AbstractTextElement) was found in HierarchicalASTVisitor.

java.lang.AssertionError: HierarchicalASTVisitor must be updated to reflect a change in the ASTNode hierarchy. No method visit(AbstractTextElement) was found in HierarchicalASTVisitor.
at org.junit.Assert.fail(Assert.java:89)
at org.eclipse.jdt.ui.tests.core.HierarchicalASTVisitorTest.checkHierarchicalASTVisitorMethodExistsFor(HierarchicalASTVisitorTest.java:522)
at org.eclipse.jdt.ui.tests.core.HierarchicalASTVisitorTest.checkAllMethodsForHierarchyExist(HierarchicalASTVisitorTest.java:495)
at org.eclipse.jdt.ui.tests.core.HierarchicalASTVisitorTest.test(HierarchicalASTVisitorTest.java:471)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)

**Comment by ktatavarthi** [comment]
@iloveeclipse I will fix this for 4.25 RC1
