### ISSUE TITLE
JDT tooltips are blank when MS Edge browser is used in Eclipse using "-Dorg.eclipse.swt.browser.DefaultType=edge"

### ISSUE THREAD

**Issue by minduch** [eclipse-jdt/eclipse.jdt.ui#248]
If running Eclipse with `-Dorg.eclipse.swt.browser.DefaultType=edge` under e.g. Windows 11 or 10, the tooltips shown by JDT in for example Java editors are empty. This is probably due to SWT issues with the `Browser` component being MS Edge and not MS Internet Explorer (or MS Edge in MSIE compatibility mode on Windows 11).

### Eclipse 2022-09 RC1 under Windows 11

Below, you will see the tooltip on a boolean variable:

<img width="395" alt="Screenshot 2022-09-03-no-content-in-JDT-tooltip-in-EDGE" src="https://user-images.githubusercontent.com/28196566/188276377-3c8046b1-c514-4455-bd21-ddb5b5ee9698.png">

If `-Dorg.eclipse.swt.browser.DefaultType=edge` is not specified, it works, both in Windows 10 and 11:

<img width="391" alt="Screenshot 2022-09-03 170708" src="https://user-images.githubusercontent.com/28196566/188276655-caccdb1d-60ef-4455-8276-1e75188b4587.png">

**Comment by ktatavarthi** [comment]
@niraj-modi Can you please provide your feedback here?

**Comment by jjohnstn** [comment]
Hi, this is an SWT issue.  I have opened: https://github.com/eclipse-platform/eclipse.platform.swt/issues/398 and copied your info.  Please track that issue and if requested, provide further details.

**Comment by jjohnstn** [comment]
Closing as issue being addressed in SWT.

**Comment by mfvalenta** [comment]
This is not an SWT issue. The behavior of the Edge browser is different than IE in the sense that whenever setText is called on the browser, A location change is issued with a URL using the data: protocol that contains the Base64 encoded version of the text. The following exception is happening because the URL is not recognized in the JavaElementLinks location listener. Because the URL parsing fails, the listener tries to invoke a hyperlink handler and sets doit to false. Change the code on line 314 to something like the following fixes the issue:

				if (nomatch) {
					try {
						if (!loc.startsWith("data:") &&  handler.handleExternalLink(new URL(loc), event.display))
							return;
						event.doit= true;
					} catch (MalformedURLException e) {
						JavaPlugin.log(e);
					}
				}

Here is the exception.

java.net.MalformedURLException: unknown protocol: data
	at java.base/java.net.URL.<init>(URL.java:681)
	at java.base/java.net.URL.<init>(URL.java:569)
	at java.base/java.net.URL.<init>(URL.java:516)
	at org.eclipse.jdt.internal.ui.viewsupport.JavaElementLinks$1.changing(JavaElementLinks.java:316)
	at org.eclipse.swt.browser.Edge.handleNavigationStarting(Edge.java:575)
	at org.eclipse.swt.browser.Edge.handleNavigationStarting(Edge.java:557)
	at org.eclipse.swt.browser.Edge.lambda$5(Edge.java:197)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3630)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

**Comment by jjohnstn** [comment]
Should the check for "data:" be instead added to the lines on 258 so if we recognize "data:" in addition to "about:blank" we call handler.handleTextSet()?

**Comment by mfvalenta** [comment]
I suspect you are right. handler.handleTextSet() should probably be called in this case.

**Comment by jjohnstn** [comment]
@mfvalenta I have posted a PR.  Could you verify this works as I don't have access to a Windows machine to test this properly?

**Comment by mfvalenta** [comment]
@jjohnstn The patch works for me.

**Comment by jjohnstn** [comment]
Thanks @mfvalenta I have merged the patch.

**Comment by ktatavarthi** [comment]
The changes have been back-ported to the branch R4_23_maintenance
