### ISSUE TITLE
PackageJavadocTests.testFailToAccessAttachedJavadoc fails in I20220920-2240 on all platforms

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.ui#272]
See https://download.eclipse.org/eclipse/downloads/drops4/I20220920-2240/testResults.php

Stack from https://download.eclipse.org/eclipse/downloads/drops4/I20220920-2240/testresults/html/org.eclipse.jdt.ui.tests_ep426I-unit-cen64-gtk3-java11_linux.gtk.x86_64_11.html

```
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.eclipse.jdt.ui.tests.hover.PackageJavadocTests.testFailToAccessAttachedJavadoc(PackageJavadocTests.java:354)
```

**Comment by akurtakov** [comment]
Haven't seen this failing in long time.
