### ISSUE TITLE
UI Freeze opening Quick Type Hierarchy

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.ui#290]
"***Quick*** Type Hierarchy" ...
I accendentially pressed Strg+t on Object.toString().
10minute freeze and i could not cancel it:-(

example stacktrace:

```
"main" #1 prio=6 os_prio=0 cpu=566609.38ms elapsed=19583.29s tid=0x00000172dcc37800 nid=0x2980 runnable  [0x000000351ff79000]
   java.lang.Thread.State: RUNNABLE
        at java.util.zip.ZipFile$Source.initCEN(java.base@11.0.16.1/ZipFile.java:1581)
        at java.util.zip.ZipFile$Source.<init>(java.base@11.0.16.1/ZipFile.java:1308)
        at java.util.zip.ZipFile$Source.get(java.base@11.0.16.1/ZipFile.java:1271)
        at java.util.zip.ZipFile$CleanableResource.<init>(java.base@11.0.16.1/ZipFile.java:733)
        at java.util.zip.ZipFile$CleanableResource.get(java.base@11.0.16.1/ZipFile.java:850)
        at java.util.zip.ZipFile.<init>(java.base@11.0.16.1/ZipFile.java:248)
        at java.util.zip.ZipFile.<init>(java.base@11.0.16.1/ZipFile.java:177)
        at java.util.zip.ZipFile.<init>(java.base@11.0.16.1/ZipFile.java:191)
        at org.eclipse.jdt.internal.core.JavaModelManager.getZipFile(JavaModelManager.java:2897)
        at org.eclipse.jdt.internal.core.nd.java.model.BinaryTypeFactory.rawReadTypeTestForExists(BinaryTypeFactory.java:145)
        at org.eclipse.jdt.internal.core.nd.java.model.BinaryTypeFactory.rawReadType(BinaryTypeFactory.java:121)
        at org.eclipse.jdt.internal.core.nd.java.model.BinaryTypeFactory.readType(BinaryTypeFactory.java:116)
        at org.eclipse.jdt.internal.core.ClassFile.getJarBinaryTypeInfo(ClassFile.java:246)
        at org.eclipse.jdt.internal.core.ClassFile.getBinaryTypeInfo(ClassFile.java:201)
        at org.eclipse.jdt.internal.core.ClassFile.buildStructure(ClassFile.java:92)
        at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:266)
        at org.eclipse.jdt.internal.core.SourceRefElement.generateInfos(SourceRefElement.java:113)
        at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:597)
        at org.eclipse.jdt.internal.core.BinaryType.getElementInfo(BinaryType.java:288)
        at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:314)
        at org.eclipse.jdt.internal.core.BinaryType.isAnonymous(BinaryType.java:732)
        at org.eclipse.jdt.internal.ui.typehierarchy.TypeHierarchyContentProvider.isAnonymous(TypeHierarchyContentProvider.java:379)
        at org.eclipse.jdt.internal.ui.typehierarchy.TypeHierarchyContentProvider.isAnonymousFromInterface(TypeHierarchyContentProvider.java:386)
        at org.eclipse.jdt.internal.ui.typehierarchy.TraditionalHierarchyViewer$TraditionalHierarchyContentProvider.getTypesInHierarchy(TraditionalHierarchyViewer.java:140)
        at org.eclipse.jdt.internal.ui.typehierarchy.TypeHierarchyContentProvider.hasTypeChildren(TypeHierarchyContentProvider.java:333)
        at org.eclipse.jdt.internal.ui.typehierarchy.TypeHierarchyContentProvider.hasChildren(TypeHierarchyContentProvider.java:275)
        at org.eclipse.jface.viewers.AbstractTreeViewer.isExpandable(AbstractTreeViewer.java:2184)
        at org.eclipse.jface.viewers.TreeViewer.isExpandable(TreeViewer.java:553)
        at org.eclipse.jface.viewers.AbstractTreeViewer.isExpandable(AbstractTreeViewer.java:2214)
        at org.eclipse.jface.viewers.AbstractTreeViewer.internalExpandToLevel(AbstractTreeViewer.java:1818)
        at org.eclipse.jface.viewers.AbstractTreeViewer.internalExpandToLevel(AbstractTreeViewer.java:1831)
        at org.eclipse.jface.viewers.AbstractTreeViewer.internalInitializeTree(AbstractTreeViewer.java:1611)
        at org.eclipse.jface.viewers.TreeViewer.internalInitializeTree(TreeViewer.java:787)
        at org.eclipse.jface.viewers.AbstractTreeViewer.lambda$1(AbstractTreeViewer.java:1595)
        at org.eclipse.jface.viewers.AbstractTreeViewer$$Lambda$677/0x00000173fcb4f840.run(Unknown Source)
        at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1398)
        at org.eclipse.jface.viewers.TreeViewer.preservingSelection(TreeViewer.java:365)
        at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1359)
        at org.eclipse.jface.viewers.AbstractTreeViewer.inputChanged(AbstractTreeViewer.java:1589)
        at org.eclipse.jface.viewers.ContentViewer.setInput(ContentViewer.java:282)
        at org.eclipse.jface.viewers.StructuredViewer.setInput(StructuredViewer.java:1632)
        at org.eclipse.jdt.internal.ui.text.AbstractInformationControl.inputChanged(AbstractInformationControl.java:618)
        at org.eclipse.jdt.internal.ui.typehierarchy.HierarchyInformationControl.setInput(HierarchyInformationControl.java:306)
        at org.eclipse.jface.text.AbstractInformationControlManager.internalShowInformationControl(AbstractInformationControlManager.java:1151)
        at org.eclipse.jface.text.AbstractInformationControlManager.presentInformation(AbstractInformationControlManager.java:1120)
        at org.eclipse.jface.text.AbstractInformationControlManager.setInformation(AbstractInformationControlManager.java:431)
        at org.eclipse.jface.text.information.InformationPresenter.computeInformation(InformationPresenter.java:321)
        at org.eclipse.jface.text.AbstractInformationControlManager.doShowInformation(AbstractInformationControlManager.java:1101)
        at org.eclipse.jface.text.AbstractInformationControlManager.showInformation(AbstractInformationControlManager.java:1091)
        at org.eclipse.jdt.internal.ui.javaeditor.JavaSourceViewer.doOperation(JavaSourceViewer.java:175)
        at org.eclipse.jdt.internal.ui.javaeditor.ClassFileEditor$5.doOperation(ClassFileEditor.java:929)
        at org.eclipse.ui.texteditor.TextOperationAction.lambda$0(TextOperationAction.java:130)
        at org.eclipse.ui.texteditor.TextOperationAction$$Lambda$1724/0x00000172c3014c40.run(Unknown Source)
        at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
        at org.eclipse.ui.texteditor.TextOperationAction.run(TextOperationAction.java:130)
        at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
        at org.eclipse.jface.commands.ActionHandler.execute(ActionHandler.java:121)
        at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
        at jdk.internal.reflect.GeneratedMethodAccessor60.invoke(Unknown Source)
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11.0.16.1/DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(java.base@11.0.16.1/Method.java:566)
        at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
        at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:317)
        at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:251)
        at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
        at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
        at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
        at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:485)
        at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
        at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:308)
        at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:580)
        at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:647)
        at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.filterKeySequenceBindings(KeyBindingDispatcher.java:439)
        at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher$KeyDownFilter.handleEvent(KeyBindingDispatcher.java:96)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
        at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1262)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1065)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1090)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1075)
        at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1117)
        at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1113)
        at org.eclipse.swt.widgets.Widget.wmChar(Widget.java:1542)
        at org.eclipse.swt.widgets.Control.WM_CHAR(Control.java:4868)
        at org.eclipse.swt.widgets.Canvas.WM_CHAR(Canvas.java:345)
        at org.eclipse.swt.widgets.Control.windowProc(Control.java:4746)
        at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:340)
        at org.eclipse.swt.widgets.Display.windowProc(Display.java:5026)
        at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3643)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
        at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
        at org.eclipse.ui.internal.Workbench$$Lambda$144/0x00000173ebe340a8.run(Unknown Source)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
        at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@11.0.16.1/Native Method)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@11.0.16.1/NativeMethodAccessorImpl.java:62)
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11.0.16.1/DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(java.base@11.0.16.1/Method.java:566)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

```

samples:
![image](https://user-images.githubusercontent.com/51790620/194348038-fa1d924d-ffa1-4882-8ea9-44d922fef3c2.png)
![image](https://user-images.githubusercontent.com/51790620/194348416-a3f8afda-e663-4719-98d4-d9ca24d16128.png)

hotspots:
![image](https://user-images.githubusercontent.com/51790620/194348643-3756f892-7c42-436a-8619-5d43aa6e6f5a.png)

**Comment by jukzi** [comment]
Still happens in Platform Workspace.

**Comment by jukzi** [comment]
With the recent performance improvements, i can not reproduce it anymore. -  Strg+t on Object.toString() takes less then a minute now and is cancelable most of the time in my workspace.
If the other watchers still can reproduce with  eclipse.buildId >= 4.31.0.I20240207-1800, please reopen.
