### ISSUE TITLE
Support Junit5 parallel test execution through RemoteTestRunner

### ISSUE THREAD

**Issue by fladdimir** [eclipse-jdt/eclipse.jdt.ui#378]
When executing Junit5 tests in parallel, the RemoteTestRunner seems to write malformed result information.
Apparently, concurrent test execution threads may write related lines of their result-reporting to the socket in a non-synchonized way?

Example output obtained from a local test run (added '// comments' to indicate problematic sections): 

```
%TESTC  2 v2
%TSTTREE2,junit5.ParallelExecutionTest,true,2,false,1,ParallelExecutionTest,,[engine:junit-jupiter]/[class:junit5.ParallelExecutionTest]
%TSTTREE3,test_1(junit5.ParallelExecutionTest),false,1,false,2,test_1(),,[engine:junit-jupiter]/[class:junit5.ParallelExecutionTest]/[method:test_1()]
%TSTTREE4,test_2(junit5.ParallelExecutionTest),false,1,false,2,test_2(),,[engine:junit-jupiter]/[class:junit5.ParallelExecutionTest]/[method:test_2()]

// 2 tests are run in parallel, both reporting their starts:
%TESTS  4,test_2(junit5.ParallelExecutionTest)
%TESTS  3,test_1(junit5.ParallelExecutionTest)

// test_2 fails and failure reporting is started:
%FAILED 4,test_2(junit5.ParallelExecutionTest)
// -> from here on, the comparison failure and trace of test_2 should follow immediately, without any interference
// however, test_1 also starts to report its failure:
%FAILED 3,test_1(junit5.ParallelExecutionTest)

// -> from here on, it is impossible to say which messages are belonging to which test:
%EXPECTS
%EXPECTS
expected_2
expected_1
%EXPECTE
%EXPECTE
%ACTUALS
%ACTUALS
actual_2
actual_1
%ACTUALE
%ACTUALE
%TRACES 
%TRACES
org.opentest4j.AssertionFailedError: expected: <expected_2> but was: <actual_2>
// [...] (shortened the stacktrace)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

%TRACEE

org.opentest4j.AssertionFailedError: expected: <expected_1> but was: <actual_1>
// [...]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

%TRACEE

// (finally both test threads report their end:)
%TESTE  4,test_2(junit5.ParallelExecutionTest)
%TESTE  3,test_1(junit5.ParallelExecutionTest)

%RUNTIME87
```

artifact / version: org.eclipse.jdt.junit.runtime-3.7.0.jar

**Comment by fladdimir** [comment]
It looks like the `FirstRunExecutionListener` (which reports the test information via its `MessageSender` (`RemoteTestRunner`)) is called concurrently from multiple test execution threads.

```java

	@Override
	public void notifyTestFailed(TestReferenceFailure failure) {
		sendMessage(failure.getTest(), failure.getStatus()); // <- write %FAILED message
                // add related comparison failure/trace messages:
		sendFailure(failure, MessageIds.TRACE_START, MessageIds.TRACE_END);
	}
        // [...]
	protected void sendFailure(TestReferenceFailure failure, String startTrace,
			String endTrace) {
		FailedComparison comparison = failure.getComparison();
		if (comparison != null)
			comparison.sendMessages(fSender);

		fSender.sendMessage(startTrace);
		fSender.sendMessage(failure.getTrace());
		fSender.sendMessage(endTrace);
		fSender.flush();
	}

```

Since calls of the underlying PrintWriter instance are synchronized, individual messages are written correctly, however, multiple related messages may be mixed up by different threads.  

To prevent this, it might be sufficient to synchronize calls of `notifyTestFailed` (the only method sending multiple related messages)?

```java
        @Override
	public synchronized void notifyTestFailed(TestReferenceFailure failure) { // [...]
```

(Please let me know in case I may help fixing this.)

**Comment by fladdimir** [comment]
> Hi @fladdimir. I think the synchronization of the notifyTestFailed method makes perfect sense. Do you want to submit a PR to go through the process or would you rather I did it?

Hi, thanks for the quick reply! I would like to do it and I will prepare a PR

**Comment by jdneo** [comment]
@fladdimir Thank you for taking look into this and deal with the upstream issue.

Will it be fine if I review this PR after the upstream changes are merged?
