### ISSUE TITLE
Problems encountered during text search. An internal error occurred during: "File Search Worker". java.lang.ClassCastException

### ISSUE THREAD

**Issue by andreasdc** [eclipse-jdt/eclipse.jdt.ui#436]
Problems encountered during text search.
An internal error occurred during: "File Search Worker".
java.lang.ClassCastException

More things break just like that, I think it's time to move to another IDE after all these years 👍

**Comment by iloveeclipse** [comment]
Can you please attach full error log? Which Eclipse version?

**Comment by andreasdc** [comment]
This is the full error, latest eclipse Version: 2022-12 (4.26.0)
Build id: 20221201-1913

**Comment by iloveeclipse** [comment]
Full error log contains stack traces and is located under <workspace>/.metadata/.log

**Comment by andreasdc** [comment]
`!ENTRY org.eclipse.core.jobs 4 0 2023-02-25 01:01:28.244
!MESSAGE Text Search
!SUBENTRY 1 org.eclipse.core.jobs 4 2 2023-02-25 01:01:28.244
!MESSAGE An internal error occurred during: "File Search Worker".
!STACK 0
java.lang.ClassCastException: class java.io.IOException cannot be cast to class java.lang.RuntimeException (java.io.IOException and java.lang.RuntimeException are in module java.base of loader 'bootstrap')
	at org.eclipse.search.internal.core.text.TextSearchVisitor$TextSearchJob.processFile(TextSearchVisitor.java:226)
	at org.eclipse.search.internal.core.text.TextSearchVisitor$TextSearchJob.run(TextSearchVisitor.java:185)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)`

**Comment by jjohnstn** [comment]
@andreasdc Now that the ClassCastException issue is fixed (latest I-builds or 4.28 M1), could you please try and reproduce the original problem so as to generate trace without internal error?
