### ISSUE TITLE
[Mac/Win] Unable to add a new source folder to a Java project using the Java Build Path properties

### ISSUE THREAD

**Issue by sclarke353** [eclipse-jdt/eclipse.jdt.ui#557]
It's not possible to add a new source folder to a Java project using the Java Build Path properties in Eclipse 2023-03.

Tested on macOS 13.3.1. 

Steps to reproduce:
Create a Java Project.
Right-Click on the Java project in the Package Explorer View and select Properties.
Select the Java Build Path properties page.
Select the Source tab.
Click Add Folder...
In the 'Source Folder Selection' dialog select 'Create New Folder...'

None of the controls in the 'New Source Folder' dialog are selectable at this point.

To close that dialog you need to first select cancel on the 'Source Folder Selection' dialog and then on the 'Properties' dialog and then the controls will be enabled and allow you to cancel it. If you try to create the folder at this point it will throw a org.eclipse.swt.SWTException: Widget is disposed error.

**Comment by sclarke353** [comment]
There are no errors logged when the 'New Source Folder' dialog is presented:
<img width="1171" alt="NewSourceFolder" src="https://user-images.githubusercontent.com/39244159/235746342-8c745b8b-6ea5-4bff-8710-717a80d4b846.png">

You will get an error if you try to add a source folder after clicking cancel on the two dialogs behind it.
org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4918)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:811)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:597)
	at org.eclipse.swt.widgets.Tree.getItemCount(Tree.java:1756)
	at org.eclipse.jface.viewers.TreeViewer.getItemCount(TreeViewer.java:197)
	at org.eclipse.jface.viewers.CheckboxTreeViewer.preservingSelection(CheckboxTreeViewer.java:401)
	at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1459)
	at org.eclipse.jface.viewers.ColumnViewer.refresh(ColumnViewer.java:526)
	at org.eclipse.jdt.internal.ui.wizards.buildpaths.MultipleFolderSelectionDialog.newFolderButtonPressed(MultipleFolderSelectionDialog.java:276)
	at org.eclipse.jdt.internal.ui.wizards.buildpaths.MultipleFolderSelectionDialog$1.widgetSelected(MultipleFolderSelectionDialog.java:229)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4646)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1547)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1532)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1325)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4413)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3989)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.jdt.internal.ui.wizards.buildpaths.CreateMultipleSourceFoldersDialog.open(CreateMultipleSourceFoldersDialog.java:191)
	at org.eclipse.jdt.internal.ui.wizards.buildpaths.SourceContainerWorkbookPage.sourcePageCustomButtonPressed(SourceContainerWorkbookPage.java:332)
	at org.eclipse.jdt.internal.ui.wizards.buildpaths.SourceContainerWorkbookPage$SourceContainerAdapter.customButtonPressed(SourceContainerWorkbookPage.java:256)
	at org.eclipse.jdt.internal.ui.wizards.dialogfields.TreeListDialogField.buttonPressed(TreeListDialogField.java:177)
	at org.eclipse.jdt.internal.ui.wizards.dialogfields.TreeListDialogField.doButtonSelected(TreeListDialogField.java:412)
	at org.eclipse.jdt.internal.ui.wizards.dialogfields.TreeListDialogField$2.widgetSelected(TreeListDialogField.java:373)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4646)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1547)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1532)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1325)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4413)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3989)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.ui.dialogs.PropertyDialogAction.run(PropertyDialogAction.java:155)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:414)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4646)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1547)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1532)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1325)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4413)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3989)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

**Comment by sclarke353** [comment]
You can also select 'Create New Folder...' multiple times:
<img width="1240" alt="MultipleDialogs" src="https://user-images.githubusercontent.com/39244159/235747798-04a6ff0a-c0a4-4f16-81af-cfbcaf708f37.png">

**Comment by iloveeclipse** [comment]
I've checked on Linux / 4.28 master and see no errors / troubles.
The related code **seem** to be untouched for years on a quick look.
May be something was fixed meanwhile - you can try latest build from https://download.eclipse.org/eclipse/downloads/.

I do not have a Mac to verify, so no idea if that is something related to the new Mac OS version or Eclipse change, you have to bisect that.

**Comment by sclarke353** [comment]
It's reproducible in the latest integration build I20230502-2040. Tested both the x86_64 and ARM macOS versions.

**Comment by iloveeclipse** [comment]
This is a regression in 4.25, works fine (tested on Windows) in 4.24.

**Comment by iloveeclipse** [comment]
Regression from https://github.com/eclipse-platform/eclipse.platform.ui/commit/70ea369e018a6df441f91555d4ca231febf2f680 / https://github.com/eclipse-platform/eclipse.platform.ui/pull/243 / https://github.com/eclipse-platform/eclipse.platform.ui/issues/242.

Reverting https://github.com/eclipse-platform/eclipse.platform.ui/commit/70ea369e018a6df441f91555d4ca231febf2f680 fixes the issue.

@jcompagner, @vogella : could you please check?

**Comment by jcompagner** [comment]
is that a wizard dialog? (seems to me that that is more a normal dialog)

But the thing is i guess incorrect parents are set there? 

I quickly tested this, and yes, the problem is incorrect parents.. 
The "new source folder" should have as its parent the "source folder selection" dialog..
It is just wrong that that is not the case..

The "new source folder" has as its parent the main application window.. but there are multiply dialogs in between...

**Comment by iloveeclipse** [comment]
> The "new source folder" should have as its parent the "source folder selection" dialog..
It is just wrong that that is not the case..

OK, thanks, that makes the fix simpler as I've thought. I will push it.

**Comment by iloveeclipse** [comment]
Fix should be available in the next nightly build on https://download.eclipse.org/eclipse/downloads/. I've checked on Windows, it looks fine, and it seem not to have any effect on Linux either. 

If it should be still broken on Mac, please reopen.

**Comment by sclarke353** [comment]
Test I20230503-1800 on macOS. All looks good. Thank you.
