### ISSUE TITLE
AnnotateAssistTest1d8.testAnnotateMethod_TypeParameter2 test failed on Mac in the I-build

### ISSUE THREAD

**Issue by ktatavarthi** [eclipse-jdt/eclipse.jdt.ui#60]
The test org.eclipse.jdt.ui.tests.quickfix.AnnotateAssistTest1d8.testAnnotateMethod_TypeParameter2 failed on Mac in the build [I20220519-0130](https://download.eclipse.org/eclipse/downloads/drops4/I20220519-0130/testResults.php), with the below error

```java.lang.NullPointerException
at java.base/java.util.Objects.requireNonNull(Objects.java:208)
at java.base/java.util.Arrays$ArrayList.<init>(Arrays.java:4137)
at java.base/java.util.Arrays.asList(Arrays.java:4122)
at org.eclipse.jdt.ui.tests.quickfix.AbstractAnnotateAssistTests.collectAnnotateProposals(AbstractAnnotateAssistTests.java:82)
at org.eclipse.jdt.ui.tests.quickfix.AnnotateAssistTest1d8.testAnnotateMethod_TypeParameter2(AnnotateAssistTest1d8.java:1133)
```
test results link : [I20220519-0130/testresults/html/org.eclipse.jdt.ui.tests_ep424I-unit-mac64-java17_macosx](https://download.eclipse.org/eclipse/downloads/drops4/I20220519-0130/testresults/html/org.eclipse.jdt.ui.tests_ep424I-unit-mac64-java17_macosx.cocoa.x86_64_17.html)

**Comment by jukzi** [comment]
random failed on  https://ci.eclipse.org/jdt/job/eclipse.jdt.ui-github/job/PR-1115/1
```
java.lang.AssertionError: 
Wrong number of proposals, is: 0, expected: 2

	at org.junit.Assert.fail(Assert.java:89)
	at org.eclipse.jdt.ui.tests.quickfix.QuickFixTest.assertNumberOfProposals(QuickFixTest.java:485)
	at org.eclipse.jdt.ui.tests.quickfix.AnnotateAssistTest1d8.testAnnotateMethod_TypeParameter2(AnnotateAssistTest1d8.java:1136)
```

may relate to https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/736

**Comment by jukzi** [comment]
also frequently fails on CI jenkins, for example https://ci.eclipse.org/jdt/job/eclipse.jdt.ui-github/job/PR-1121/3
