### ISSUE TITLE
AnnotateAssistTest1d5. testAnnotateParameter_Array1 failed

### ISSUE THREAD

**Issue by noopur2507** [eclipse-jdt/eclipse.jdt.ui#608]
I20230531-1800

ep428I-unit-mac64-java17
macosx.cocoa.x86_64
17

java.lang.NullPointerException
at java.base/java.util.Objects.requireNonNull(Objects.java:208)
at java.base/java.util.Arrays$ArrayList.<init>(Arrays.java:4137)
at java.base/java.util.Arrays.asList(Arrays.java:4122)
at org.eclipse.jdt.ui.tests.quickfix.AbstractAnnotateAssistTests.collectAnnotateProposals(AbstractAnnotateAssistTests.java:82)
at org.eclipse.jdt.ui.tests.quickfix.AnnotateAssistTest1d5.testAnnotateParameter_Array1(AnnotateAssistTest1d5.java:316)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by stephan-herrmann** [comment]
I cannot reproduce and hence all I can do is analyze the code:

* `ExternalNullAnnotationQuickAssistProcessor.computeQuickAssistProposals(IQuickAssistInvocationContext)` returned null.
* There are two such exits
  * The first one could result from either `cu==null` (I don't think that possible though), or `classFile.getSource() == null`
  * The second exit would have logged a `JavaModelException`. As this has not been reported, I assume the former.
* If indeed `classFile.getSource()` answered `null`, it could either mean the classfile was not valid (I cannot see any reason for this), or we were facing an issue with buffer management.

If buffer management is the problem, indeed, then I cannot even start to guess a cause. Corrupt cache, or SourceMapper's failure to find sources?

Finding nothing specific to the annotate assist, I'm stepping back from this issue.

**Comment by trancexpress** [comment]
Another fail here: https://download.eclipse.org/eclipse/downloads/drops4/I20260430-1800/testresults/html/org.eclipse.jdt.ui.tests_ep440I-unit-linux-x86_64-java26_linux.gtk.x86_64_26.html

```
	cu=[Working copy] X.class [in pack.age [in lib.jar [in TestSetupProject1d8]]] package pack.age interface X java.lang.String test(int[][], java.util.List<java.lang.String>) source=null

java.lang.AssertionError: cu=[Working copy] X.class [in pack.age [in lib.jar [in TestSetupProject1d8]]]
package pack.age
interface X
java.lang.String test(int[][], java.util.List<java.lang.String>) source=null
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.eclipse.jdt.ui.tests.quickfix.AbstractAnnotateAssistTests.collectAnnotateProposals(AbstractAnnotateAssistTests.java:123)
at org.eclipse.jdt.ui.tests.quickfix.AnnotateAssistTest1d8.testAnnotateParameter_Array4(AnnotateAssistTest1d8.java:557)
at java.base/java.lang.reflect.Method.invoke(Method.java:565) 
```

Nothing in the workspace log: https://download.eclipse.org/eclipse/downloads/drops4/I20260430-1800/testresults/ep440I-unit-linux-x86_64-java26_linux.gtk.x86_64_26/org.eclipse.jdt.ui.tests.AutomatedSuite.txt

```
!ENTRY org.eclipse.jdt.ui.tests 1 0 2026-05-01 01:04:01.130
!MESSAGE testAnnotateParameter_Array4 STARTING

!ENTRY org.eclipse.jdt.ui.tests 1 0 2026-05-01 01:04:01.336
!MESSAGE testAnnotateParameter_Array4 DONE: FAILED
```

Seems like there were no proposals, but the test was expecting some.
