### ISSUE TITLE
JavadocHover logs Java Model Exception

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.ui#668]
Logged while editing sourcecode - i think a Hover should be more silent:
```
Java Model Exception: Error in Java Model (code 1006): <module:java.xml> is not on its project's build path
	at org.eclipse.jdt.internal.core.PackageFragmentRoot.getResolvedClasspathEntry(PackageFragmentRoot.java:630)
	at org.eclipse.jdt.internal.corext.javadoc.JavaDocLocations.getJavadocBaseLocation(JavaDocLocations.java:203)
	at org.eclipse.jdt.internal.corext.javadoc.JavaDocLocations.getJavadocLocation(JavaDocLocations.java:222)
	at org.eclipse.jdt.ui.JavaUI.getJavadocLocation(JavaUI.java:1080)
	at org.eclipse.jdt.internal.corext.javadoc.JavaDocLocations.getBaseURL(JavaDocLocations.java:546)
	at org.eclipse.jdt.internal.ui.text.java.hover.JavadocHover.getHoverInfo(JavadocHover.java:759)
	at org.eclipse.jdt.internal.ui.text.java.hover.JavadocHover.internalGetHoverInfo(JavadocHover.java:671)
	at org.eclipse.jdt.internal.ui.text.java.hover.JavadocHover.getHoverInfo2(JavadocHover.java:663)
	at org.eclipse.jdt.internal.ui.text.java.hover.BestMatchHover.getHoverInfo2(BestMatchHover.java:163)
	at org.eclipse.jdt.internal.ui.text.java.hover.BestMatchHover.getHoverInfo2(BestMatchHover.java:130)
	at org.eclipse.jdt.internal.ui.text.java.hover.JavaEditorTextHoverProxy.getHoverInfo2(JavaEditorTextHoverProxy.java:89)
	at org.eclipse.jface.text.TextViewerHoverManager$1.run(TextViewerHoverManager.java:155)
eclipse.buildId=4.29.0.I20230709-1800
java.version=17.0.7
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Command-line arguments:  -os win32 -ws win32 -arch x86_64
```
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/ce8c6d8d-83ed-4dc0-a930-546e2bafd463)

On the other hand i wonder why there was no compiler error visible at the same time.

**Comment by jukzi** [comment]
closing: do not know how to reproduce.
