### ISSUE TITLE
Removing .p2 folder makes Eclipse unlaunchable

### ISSUE THREAD

**Issue by andreasdc** [eclipse-jdt/eclipse.jdt.ui#719]
I wanted to delete .p2 folder, but it gives me this error. This folder is 3gb in size for me and looks weird, I want to free up my space.
Eclipse executable launcher error: Unable to locate companion shared library

**Comment by andreasdc** [comment]
I see most of it is pool/plugins folder, which has ton of old files and folders.

**Comment by jjohnstn** [comment]
Hi @andreasdc You cannot remove that folder.  Please see: https://stackoverflow.com/questions/62230297/what-are-m2-and-p2-folders-and-can-i-delete-them

I'm closing this issue.

**Comment by andreasdc** [comment]
I have error on Cleanup Agent.

java.lang.reflect.InvocationTargetException
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:395)
	at org.eclipse.jface.dialogs.ProgressMonitorDialog.run(ProgressMonitorDialog.java:470)
	at org.eclipse.oomph.p2.internal.ui.AgentManagerComposite.cleanup(AgentManagerComposite.java:593)
	at org.eclipse.oomph.p2.internal.ui.AgentManagerComposite$7.widgetSelected(AgentManagerComposite.java:281)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4274)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3660)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.oomph.setup.internal.installer.SimpleInstallerDialog.manageBundlePools(SimpleInstallerDialog.java:962)
	at org.eclipse.oomph.setup.internal.installer.SimpleInstallerDialog$14.widgetSelected(SimpleInstallerDialog.java:722)
	at org.eclipse.oomph.internal.ui.FlatButton.notifySelectionListeners(FlatButton.java:644)
	at org.eclipse.oomph.internal.ui.FlatButton.onMouseUp(FlatButton.java:603)
	at org.eclipse.oomph.internal.ui.FlatButton.handleEvent(FlatButton.java:497)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4274)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3660)
	at org.eclipse.oomph.setup.internal.installer.Installer.runEventLoop(Installer.java:359)
	at org.eclipse.oomph.setup.internal.installer.SimpleInstallerDialog.runEventLoop(SimpleInstallerDialog.java:990)
	at org.eclipse.oomph.setup.internal.installer.AbstractSimpleDialog.show(AbstractSimpleDialog.java:195)
	at org.eclipse.oomph.setup.internal.installer.InstallerApplication.run(InstallerApplication.java:295)
	at org.eclipse.oomph.setup.internal.installer.InstallerApplication.start(InstallerApplication.java:401)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
Caused by: org.eclipse.oomph.p2.P2Exception: Profile does not exist: C__Users__eclipse
	at org.eclipse.oomph.p2.internal.core.ProfileImpl.getProfileSafe(ProfileImpl.java:299)
	at org.eclipse.oomph.p2.internal.core.ProfileImpl.doSetDelegate(ProfileImpl.java:291)
	at org.eclipse.oomph.p2.internal.core.ProfileImpl.getDelegate(ProfileImpl.java:250)
	at org.eclipse.oomph.p2.internal.core.ProfileImpl.getDelegate(ProfileImpl.java:238)
	at org.eclipse.oomph.p2.internal.core.ProfileImpl.getProperty(ProfileImpl.java:409)
	at org.eclipse.oomph.p2.internal.core.AgentAnalyzer$AnalyzedProfile.<init>(AgentAnalyzer.java:827)
	at org.eclipse.oomph.p2.internal.core.AgentAnalyzer$AnalyzedBundlePool.addProfile(AgentAnalyzer.java:520)
	at org.eclipse.oomph.p2.internal.core.AgentAnalyzer.<init>(AgentAnalyzer.java:120)
	at org.eclipse.oomph.p2.internal.ui.AgentManagerComposite$16.run(AgentManagerComposite.java:600)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
