### ISSUE TITLE
46 test fails in CodeCompletionTest, JavadocCompletionTest, TypeCompletionTest in I20230824-0400

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.ui#735]
https://download.eclipse.org/eclipse/downloads/drops4/I20230824-0400/testresults/html/org.eclipse.jdt.text.tests_ep429I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html

All are very similar, is if they are unable to find JDK classes

I wonder if that has relationship to the "DetectVMInstallationsJob" job / similar to https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1190

```
no proposal starting with "{@link DateFormat}"

java.lang.AssertionError: no proposal starting with "{@link DateFormat}"
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.eclipse.jdt.text.tests.contentassist.AbstractCompletionTest.findNonNullProposal(AbstractCompletionTest.java:555)
at org.eclipse.jdt.text.tests.contentassist.AbstractCompletionTest.assertProposal(AbstractCompletionTest.java:357)
at org.eclipse.jdt.text.tests.contentassist.AbstractCompletionTest.assertTypeJavadocProposal(AbstractCompletionTest.java:331)
at org.eclipse.jdt.text.tests.contentassist.JavadocCompletionTest.testDirectLinkImportsOnExistingImportCamelCase(JavadocCompletionTest.java:201)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

```
no proposal starting with "List "

java.lang.AssertionError: no proposal starting with "List "
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.eclipse.jdt.text.tests.contentassist.AbstractCompletionTest.findNonNullProposal(AbstractCompletionTest.java:555)
at org.eclipse.jdt.text.tests.contentassist.AbstractCompletionTest.assertProposal(AbstractCompletionTest.java:357)
at org.eclipse.jdt.text.tests.contentassist.AbstractCompletionTest.assertTypeJavadocProposal(AbstractCompletionTest.java:331)
at org.eclipse.jdt.text.tests.contentassist.JavadocCompletionTest.testLinkType(JavadocCompletionTest.java:148)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

```
no proposal starting with "Random "

java.lang.AssertionError: no proposal starting with "Random "
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.eclipse.jdt.text.tests.contentassist.AbstractCompletionTest.findNonNullProposal(AbstractCompletionTest.java:555)
at org.eclipse.jdt.text.tests.contentassist.AbstractCompletionTest.assertProposal(AbstractCompletionTest.java:357)
at org.eclipse.jdt.text.tests.contentassist.AbstractCompletionTest.assertMethodBodyProposal(AbstractCompletionTest.java:242)
at org.eclipse.jdt.text.tests.contentassist.TypeCompletionTest.testNoQualifierRemovalWithImport(TypeCompletionTest.java:88)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

**Comment by noopur2507** [comment]
These haven't failed since then. The issue can be reopened if it repeats.

**Comment by jukzi** [comment]
According to https://bugs.eclipse.org/bugs/show_bug.cgi?id=186554 such errors can be worked around with org.eclipse.jdt.text.tests.contentassist.AbstractCompletionTest.waitBeforeCoreCompletion() to sleep longer. However i would rather love to see the sleep replaced with a condition to wait on. 
Locally i can not reproduce the error even when the sleep is totally removed. So i don't know which condition to wait for.

**Comment by trancexpress** [comment]
Here is what Copilot advises:



> Root Cause
>
>The tests in CodeCompletionTest, JavadocCompletionTest, and TypeCompletionTest fail intermittently because waitBeforeCoreCompletion() only waits for the
Java indexer to be ready (via mustPerformDummySearch()) but not for other background jobs.
>
> Background jobs like DetectVMInstallationsJob (from JDT launching) can still be running after the indexer finishes. When they complete, they modify
JVM/classpath setup ￢ﾀﾔ but by then, the completion engine has already run with an incomplete classpath, finding zero proposals for JDK types like 
DateFormat, List, Random.
>
> The fixed sleep of Thread.sleep(2000) was only active when fWaitBeforeCompleting=true or camel-case matching was enabled ￢ﾀﾔ neither of which is true by
default ￢ﾀﾔ so no extra wait was happening.
>
> Fix
>
> Added an unconditional call to EditorTestHelper.joinJobs(0, 15000, 100) after the indexer wait. This:
>
> - Waits condition-based (polls every 100ms) until all background jobs are quiet, rather than using an arbitrary fixed sleep
> - Times out after 15 seconds to avoid hanging if a system job never stops
> - EditorTestHelper was already imported in AbstractCompletionTest, so no new imports are needed
>
> The existing Thread.sleep(2000) for camel-case/manual wait scenarios is preserved for backward compatibility.

```
diff --git a/org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/contentassist/AbstractCompletionTest.java b/org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/contentassist/AbstractCompletionTest.java
index 2aa33d817f..a2f2f0d8ec 100644
--- a/org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/contentassist/AbstractCompletionTest.java
+++ b/org.eclipse.jdt.text.tests/src/org/eclipse/jdt/text/tests/contentassist/AbstractCompletionTest.java
@@ -605,9 +605,9 @@ public abstract class AbstractCompletionTest {
        }
 
        /**
-        * Invokes {@link Thread#sleep(long)} if {@link #waitBeforeCompleting(boolean)} was set to
-        * <code>true</code> or camel case completions are enabled. For some reasons, inner types and
-        * camel case matches don't show up otherwise.
+        * Waits for the indexer and all background jobs (e.g. VM detection) to settle before
+        * triggering code completion. For some reasons, inner types and camel case matches don't show
+        * up otherwise.
         *
         * @since 3.2
         */
@@ -619,13 +619,17 @@ public abstract class AbstractCompletionTest {
                        fail("could not synchronize with indexer");
                }
 
-           if (fWaitBeforeCompleting || JavaCore.ENABLED.equals(JavaCore.getOption(JavaCore.CODEASSIST_CAMEL_CASE_MATCH))) {
+               // Wait for background jobs (e.g. DetectVMInstallationsJob) to settle so that
+               // classpath/VM setup is complete before triggering completion.
+               EditorTestHelper.joinJobs(0, 15000, 100);
+
+               if (fWaitBeforeCompleting || JavaCore.ENABLED.equals(JavaCore.getOption(JavaCore.CODEASSIST_CAMEL_CASE_MATCH))) {
                        try {
                                Thread.sleep(2000);
                        } catch (InterruptedException x) {
                        }
                }
-    }
+       }
 
        protected String getContentType() {
                return IDocument.DEFAULT_CONTENT_TYPE;
```

I do wonder why there would be 40+ test fails in one session... If it was just a synchronization problem, I'd expect only a few fails at most in a session...

The log file unfortunately doesn't mention test starts/ends...
