### ISSUE TITLE
RemoteTestRunner : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by sbernard31** [eclipse-jdt/eclipse.jdt.ui#737]
I'm using **Java Development Tools UI**(org.eclipse.jdt.ui) v3.29.0.v20230525-0728

My project target Java7 as minimal version. 
(I know this is not maintain anymore but this is just the minimal version and there is good reason to keep to Java7 as minimal version)

When I launch my JUnit tests (based on JUnit 4 which is compatible with java 7) in eclipse, I get : 
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/eclipse/jdt/internal/junit/runner/RemoteTestRunner : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
```

I know I can compile with more recent JVM and still target old JDK with [`-release`](https://openjdk.org/jeps/247) but at some time I need to check if my binary works with Java7 and so I need to launch my Junit tests with it.

**Comment by iloveeclipse** [comment]
> but at some time I need to check if my binary works with Java7 and so I need to launch my Junit tests with it.

Please use older Eclipse SDK to work with older Java versions. We can't keep support for Java 7 and Java 20+ at same time.

**Comment by sbernard31** [comment]
@iloveeclipse, thx for prompt answer. :pray: 

> Please use older Eclipse SDK to work with older Java versions. 

Just in case, do you know the last compatible version ? 


> We can't keep support for Java 7 and Java 20+ at same time.

Just for my knowledge, does it means there is incompatibility between those both Java version ? Do you have any information/ressources about it ? I did a quick research and didn't find anything.

**Comment by iloveeclipse** [comment]
> Just for my knowledge, does it means there is incompatibility between those both Java version ? Do you have any information/ressources about it ?

There were breaking security manager related changes in one of 9+ JDK's if I remember it right, plus building all that code with the support of older & new API's is not trivial. Additionally we simply too short on resources to provide any reasonable support for older releases.

> Just in case, do you know the last compatible version ?

Have to look into source & have no time to do that, sorry, please find it by trial and error.

**Comment by sbernard31** [comment]
I understand, thx for your help.
