### ISSUE TITLE
NPE in org.eclipse.jdt.internal.corext.util.JavaModelUtil.isEditable

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.ui#738]
i have no clue how to reproduce but found it in my log:

Version: 2022-12 (4.26)
Build id: I20221123-1800
```
!ENTRY org.eclipse.jdt.core 4 2 2023-08-25 10:16:38.476
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jdt.core".
!STACK 0
java.lang.NullPointerException: Cannot invoke "org.eclipse.core.resources.ResourceAttributes.isReadOnly()" because the return value of "org.eclipse.core.resources.IResource.getResourceAttributes()" is null
	at org.eclipse.jdt.internal.corext.util.JavaModelUtil.isEditable(JavaModelUtil.java:532)
	at org.eclipse.jdt.internal.ui.compare.JavaStructureDiffViewer.isEditable(JavaStructureDiffViewer.java:318)
	at org.eclipse.jdt.internal.ui.compare.JavaStructureDiffViewer.addAffectedElement(JavaStructureDiffViewer.java:306)
	at org.eclipse.jdt.internal.ui.compare.JavaStructureDiffViewer.findAffectedElement(JavaStructureDiffViewer.java:290)
	at org.eclipse.jdt.internal.ui.compare.JavaStructureDiffViewer.elementChanged(JavaStructureDiffViewer.java:266)
	at org.eclipse.jdt.internal.core.DeltaProcessor$3.run(DeltaProcessor.java:1755)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.internal.core.DeltaProcessor.notifyListeners(DeltaProcessor.java:1743)
	at org.eclipse.jdt.internal.core.DeltaProcessor.firePostChangeDelta(DeltaProcessor.java:1576)
	at org.eclipse.jdt.internal.core.DeltaProcessor.fire(DeltaProcessor.java:1552)
	at org.eclipse.jdt.internal.core.DeltaProcessor.notifyAndFire(DeltaProcessor.java:2273)
	at org.eclipse.jdt.internal.core.DeltaProcessor.resourceChanged(DeltaProcessor.java:2163)
	at org.eclipse.jdt.internal.core.DeltaProcessingState.resourceChanged(DeltaProcessingState.java:501)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:307)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:297)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:160)
	at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:388)
	at org.eclipse.core.internal.resources.Workspace.checkpoint(Workspace.java:584)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation.lambda$0(PerformChangeOperation.java:263)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2380)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2405)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation.executeChange(PerformChangeOperation.java:295)
	at org.eclipse.ltk.internal.ui.refactoring.UIPerformChangeOperation.executeChange(UIPerformChangeOperation.java:94)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation.run(PerformChangeOperation.java:219)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2380)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2405)
	at org.eclipse.ltk.internal.ui.refactoring.WorkbenchRunnableAdapter.run(WorkbenchRunnableAdapter.java:89)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

```

**Comment by robstryker** [comment]
Looks reasonable.
