### ISSUE TITLE
Intermittent test failures in I-builds : testHierarchicalJUnit and markImplementOccurrences3

### ISSUE THREAD

**Issue by ktatavarthi** [eclipse-jdt/eclipse.jdt.ui#80]
This is an issue tracking [Bug 562654](https://bugs.eclipse.org/bugs/show_bug.cgi?id=562654) - Intermittent test failures in I-builds : testHierarchicalJUnit, testFormatChanges02, markImplementOccurrences3

The below tests fail randomly in the nightly builds
- org.eclipse.jdt.ui.tests.refactoring.RenamePackageTests.testHierarchicalJUnit
- org.eclipse.jdt.text.tests.MarkOccurrenceTest.markImplementOccurrences3

Created the below issue for random failure of org.eclipse.jdt.ui.tests.quickfix.SaveParticipantTest.testFormatChanges02
-  https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/79

**Comment by ktatavarthi** [comment]
The test org.eclipse.jdt.ui.tests.refactoring.RenamePackageTests.testHierarchicalJUnit failed on [Windows ](https://download.eclipse.org/eclipse/downloads/drops4/I20220601-1800/testresults/html/org.eclipse.jdt.ui.tests.refactoring_ep424I-unit-win32-java11_win32.win32.x86_64_11.html) in the I-Build [I20220601-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20220601-1800/testResults.php) with the below error

```
Problems encountered while moving resources.

Java Model Exception: Core Exception [code 4] Problems encountered while moving resources.
at org.eclipse.jdt.internal.core.MultiOperation.processElements(MultiOperation.java:180)
at org.eclipse.jdt.internal.core.CopyResourceElementsOperation.processElements(CopyResourceElementsOperation.java:436)
at org.eclipse.jdt.internal.core.MultiOperation.executeOperation(MultiOperation.java:95)
at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:740)
at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2380)
at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2405)
at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:811)
at org.eclipse.jdt.internal.core.JavaModel.rename(JavaModel.java:296)
at org.eclipse.jdt.internal.core.PackageFragment.rename(PackageFragment.java:533)
at org.eclipse.jdt.internal.corext.refactoring.changes.RenamePackageChange.renamePackage(RenamePackageChange.java:210)
at org.eclipse.jdt.internal.corext.refactoring.changes.RenamePackageChange.doRename(RenamePackageChange.java:137)
at org.eclipse.jdt.internal.corext.refactoring.AbstractJavaElementRenameChange.perform(AbstractJavaElementRenameChange.java:92)
at org.eclipse.ltk.core.refactoring.CompositeChange.perform(CompositeChange.java:281)
at org.eclipse.jdt.internal.corext.refactoring.changes.DynamicValidationStateChange.access$0(DynamicValidationStateChange.java:1)
at org.eclipse.jdt.internal.corext.refactoring.changes.DynamicValidationStateChange.lambda$0(DynamicValidationStateChange.java:105)
at org.eclipse.jdt.internal.core.BatchOperation.executeOperation(BatchOperation.java:41)
at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:740)
at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2380)
at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2405)
at org.eclipse.jdt.core.JavaCore.run(JavaCore.java:5929)
at org.eclipse.jdt.internal.corext.refactoring.changes.DynamicValidationStateChange.perform(DynamicValidationStateChange.java:106)
at org.eclipse.ltk.core.refactoring.CompositeChange.perform(CompositeChange.java:281)
at org.eclipse.ltk.core.refactoring.PerformChangeOperation.lambda$0(PerformChangeOperation.java:258)
at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2380)
at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2405)
at org.eclipse.ltk.core.refactoring.PerformChangeOperation.executeChange(PerformChangeOperation.java:295)
at org.eclipse.ltk.core.refactoring.PerformChangeOperation.run(PerformChangeOperation.java:224)
at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2380)
at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2400)
at org.eclipse.jdt.ui.tests.refactoring.RenamePackageTests.testHierarchicalJUnit(RenamePackageTests.java:1014)
```
