### ISSUE TITLE
Failure of test AnnotateAssistTest1d5.testAnnotateConstructorParameter

### ISSUE THREAD

**Issue by fedejeanne** [eclipse-jdt/eclipse.jdt.ui#811]
Failed on [this check](https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/808/checks?check_run_id=16954822326) of #808 

```java
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at java.base/java.util.Arrays$ArrayList.<init>(Arrays.java:4137)
	at java.base/java.util.Arrays.asList(Arrays.java:4122)
	at org.eclipse.jdt.ui.tests.quickfix.AbstractAnnotateAssistTests.collectAnnotateProposals(AbstractAnnotateAssistTests.java:82)
	at org.eclipse.jdt.ui.tests.quickfix.AnnotateAssistTest1d5.testAnnotateConstructorParameter(AnnotateAssistTest1d5.java:460)
```

**Comment by fedejeanne** [comment]
Could someone with enough permissions please add the "help wanted" and "test" tags here? I'm working on some other stuff right now so I won't be able to work on this any time soon.
Thank you.
