### ISSUE TITLE
Unexpected runtime error while computing a text hover

### ISSUE THREAD

**Issue by GiacomoCau** [eclipse-jdt/eclipse.jdt.ui#819]
eclipse.buildId=4.29.0.20230907-1200
java.version=17.0.8.1
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=it_IT
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

org.eclipse.jface.text
Error
Fri Sep 22 11:08:39 CEST 2023
Unexpected runtime error while computing a text hover

java.lang.ClassCastException: class org.eclipse.jdt.internal.compiler.ast.LocalDeclaration cannot be cast to class org.eclipse.jdt.internal.compiler.ast.MethodDeclaration (org.eclipse.jdt.internal.compiler.ast.LocalDeclaration and org.eclipse.jdt.internal.compiler.ast.MethodDeclaration are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @26393026)
	at org.eclipse.jdt.internal.compiler.parser.Parser.consumeMethodDeclaration(Parser.java:5247)
	at org.eclipse.jdt.internal.codeassist.impl.AssistParser.consumeMethodDeclaration(AssistParser.java:822)
	at org.eclipse.jdt.internal.compiler.parser.Parser.consumeRule(Parser.java:7149)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:13145)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:13400)
	at org.eclipse.jdt.internal.codeassist.select.SelectionParser.parse(SelectionParser.java:1665)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:13357)
	at org.eclipse.jdt.internal.compiler.parser.Parser.dietParse(Parser.java:11743)
	at org.eclipse.jdt.internal.codeassist.select.SelectionParser.dietParse(SelectionParser.java:1489)
	at org.eclipse.jdt.internal.codeassist.SelectionEngine.select(SelectionEngine.java:994)
	at org.eclipse.jdt.internal.core.Openable.codeSelect(Openable.java:167)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeSelect(CompilationUnit.java:389)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeSelect(CompilationUnit.java:382)
	at org.eclipse.jdt.internal.ui.text.java.hover.AbstractJavaEditorTextHover.getJavaElementsAt(AbstractJavaEditorTextHover.java:121)
	at org.eclipse.jdt.internal.ui.text.java.hover.JavadocHover.internalGetHoverInfo(JavadocHover.java:667)
	at org.eclipse.jdt.internal.ui.text.java.hover.JavadocHover.getHoverInfo2(JavadocHover.java:663)
	at org.eclipse.jdt.internal.ui.text.java.hover.BestMatchHover.getHoverInfo2(BestMatchHover.java:163)
	at org.eclipse.jdt.internal.ui.text.java.hover.BestMatchHover.getHoverInfo2(BestMatchHover.java:130)
	at org.eclipse.jdt.internal.ui.text.java.hover.JavaEditorTextHoverProxy.getHoverInfo2(JavaEditorTextHoverProxy.java:89)
	at org.eclipse.jface.text.TextViewerHoverManager$1.run(TextViewerHoverManager.java:155)

**Comment by GiacomoCau** [comment]
Occurs when you hover over most comments, method parameters and local declarations with the mouse only by editing this project's [java file](https://github.com/GiacomoCau/Wat/blob/main/src/Wat/Vm.java)
I was unable to understand what triggers the problem and build a reduced example.

**Comment by iloveeclipse** [comment]
Just in case, could you please try latest 4.30 nightly build: https://download.eclipse.org/eclipse/downloads/drops4/I20230922-0140 ?

**Comment by GiacomoCau** [comment]
Thanks Andrey,
It seems that the problem has been resolved on this version.
I tried again after recompiling the project with java 21 and javaCC 7 and there are no reports whatsoever in the Error log.
Do you have any idea when it will be released?

**Comment by GiacomoCau** [comment]
or rather, if the fixes will end up in a new release of 4.29?

**Comment by iloveeclipse** [comment]
> or rather, if the fixes will end up in a new release of 4.29?

No. Eclipse doesn't provide maintenance releases, but we ship a new version every 3 months.
