### ISSUE TITLE
Eclipse sometimes throws Exception on simple quick fix

### ISSUE THREAD

**Issue by Sciuriware** [eclipse-jdt/eclipse.jdt.ui#887]
Refer to attachments:
1) very simple method head with one parameter and return type,
2) result of CMD/1 (quick fix),
3) I clicked 'details' (nothing new shown).
![EclipseException1](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/121790387/0e9794f2-9b9c-40ae-8383-d84396ce02c6)
![EclipseException2](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/121790387/31afa8b2-9f6a-44c8-82d9-12ee21618c4c)
![EclipseException3](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/121790387/86a4b301-d885-4591-a18c-03f5add3c933)

No source was lost, however ... not yet.
;JOOP!

**Comment by Sciuriware** [comment]
P.S.: Eclipse version 4.30M1 running on APPLE iMac running MacOS 11.7.10 (Big Sur), with JDK 20.0.2 library.
;JOOP!

**Comment by iloveeclipse** [comment]
Please provide **full stack trace** of the reported error (you will find it in the Error Log view), and ideally isolated code that shows the problem. Screenshots of both are not very helpful.

**Comment by Sciuriware** [comment]
Contents of the log.
[ErrorLog.txt](https://github.com/eclipse-jdt/eclipse.jdt.ui/files/13207247/ErrorLog.txt)

Trying to isolate the code into a new source file.
;JOOP!

**Comment by iloveeclipse** [comment]
OK, relevant part is:

```
eclipse.buildId=4.30.0.I20230927-1800
java.version=20.0.2
```

```
!ENTRY org.eclipse.jdt.ui 4 10001 2023-10-30 16:54:48.058
!MESSAGE Internal Error
!STACK 1
org.eclipse.core.runtime.CoreException: org.eclipse.jface.text.BadLocationException
	at org.eclipse.jdt.internal.ui.text.correction.proposals.LinkedCorrectionProposal.performChange(LinkedCorrectionProposal.java:175)
	at org.eclipse.jdt.ui.text.java.correction.CUCorrectionProposal.apply(CUCorrectionProposal.java:200)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.insertProposal(CompletionProposalPopup.java:1004)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.insertSelectedProposalWithMask(CompletionProposalPopup.java:951)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup$3.widgetDefaultSelected(CompletionProposalPopup.java:697)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:123)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4646)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1547)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1532)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1325)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4413)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3989)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:645)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:552)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
Caused by: org.eclipse.jface.text.BadLocationException
	at org.eclipse.jface.text.link.LinkedPositionGroup.enforceDisjoint(LinkedPositionGroup.java:162)
	at org.eclipse.jface.text.link.LinkedPositionGroup.enforceDisjoint(LinkedPositionGroup.java:175)
	at org.eclipse.jface.text.link.LinkedModeModel.enforceDisjoint(LinkedModeModel.java:305)
	at org.eclipse.jface.text.link.LinkedModeModel.addGroup(LinkedModeModel.java:415)
	at org.eclipse.jdt.internal.ui.viewsupport.LinkedProposalModelPresenter.enterLinkedMode(LinkedProposalModelPresenter.java:104)
	at org.eclipse.jdt.internal.ui.text.correction.proposals.LinkedCorrectionProposal.performChange(LinkedCorrectionProposal.java:164)
	... 32 more
!SUBENTRY 1 org.eclipse.jdt.ui 4 4 2023-10-30 16:54:48.059
!MESSAGE org.eclipse.jface.text.BadLocationException
!STACK 0
org.eclipse.jface.text.BadLocationException
	at org.eclipse.jface.text.link.LinkedPositionGroup.enforceDisjoint(LinkedPositionGroup.java:162)
	at org.eclipse.jface.text.link.LinkedPositionGroup.enforceDisjoint(LinkedPositionGroup.java:175)
	at org.eclipse.jface.text.link.LinkedModeModel.enforceDisjoint(LinkedModeModel.java:305)
	at org.eclipse.jface.text.link.LinkedModeModel.addGroup(LinkedModeModel.java:415)
	at org.eclipse.jdt.internal.ui.viewsupport.LinkedProposalModelPresenter.enterLinkedMode(LinkedProposalModelPresenter.java:104)
	at org.eclipse.jdt.internal.ui.text.correction.proposals.LinkedCorrectionProposal.performChange(LinkedCorrectionProposal.java:164)
	at org.eclipse.jdt.ui.text.java.correction.CUCorrectionProposal.apply(CUCorrectionProposal.java:200)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.insertProposal(CompletionProposalPopup.java:1004)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.insertSelectedProposalWithMask(CompletionProposalPopup.java:951)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup$3.widgetDefaultSelected(CompletionProposalPopup.java:697)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:123)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4646)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1547)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1532)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1325)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4413)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3989)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:645)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:552)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
```

I honestly don't see anything obvious in this stack, but I'm not familiar with the code in question.

@robstryker : I see that you've changed few things in LinkedProposalModel & Co code in the past, might be you have an idea what is going on here.

**Comment by robstryker** [comment]
I'll have a look at this tomorrow and see if there's anything obvious. I must admit I'm not an expert on this part of the code, but I did poke around it so it's worth it for me to dive a bit.

**Comment by jjohnstn** [comment]
@Sciuriware Could you please try a recent I-build?  On 09-27 we reverted some changes to refactor proposal code which caused a BadLocation exception due to duplicated text edits.  We have since replaced that refactoring and it should all work fine now.

**Comment by robstryker** [comment]
So I've tried to replicate, but I can't.  I'm using linux, and don't have access to a mac. 

I've attempted to replicate with an m1 installation, as well as running eclipse.jdt.ui from the m1 tag and eclipse.jdt.core from my best guess of what the m1 tag was (because eclipse.jdt.core doesn't seem to tag much at all...)

I see no exceptions or anything in the error log and have been unable to replicate. 

There was a BadLocation exception issue occurring on the day we tagged m1 for release (9/27), and a reversion of the commit at fault, but it's not clear to me whether the reversion made it into the release, because the m1 tag was the commit before the reversion. I strongly suspect the reversion DID make it into the release and thus m1 shouldn't be having any such issues. If M1 is still displaying issues like this, even though the faulty code was reverted before (we think) release, then it could be a new or unique issue. 

But as @jjohnstn  says, we did end up fixing all of the issues and so recent ibuilds should provide a better indication as to what the current state is.

**Comment by Sciuriware** [comment]
@jjohnstn :: downloaded I20231031-0530,
Replayed the problem ..... NO Exception thrown.
Is it risky to continue my development with that version?
Looking out for the next major release.
Thanks for your effort.
;JOOP!

**Comment by jjohnstn** [comment]
Hi @Sciuriware Using any I-build is not without its risks as new features/fixes are being added and not necessarily exposed to the rigorous testing once released, however, bugs are discovered even in major releases.  If you use I-builds for development, it is recommended to update to the latest I-build when you run into any problem as it is entirely possible the problem is already fixed as in this case.
