### ISSUE TITLE
9 JavaLeakTest failed in I20231107-1800

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.ui#908]
https://download.eclipse.org/eclipse/downloads/drops4/I20231107-1800/testResults.php
for example
```
java.lang.AssertionError: Expected instance count: 1, actual: 2
Element 0
org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitEditor
org.eclipse.jdt.internal.ui.javaeditor.ASTProvider#fActiveEditor -> org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitEditor@71c87181
org.eclipse.jdt.internal.ui.JavaPlugin#fASTProvider -> org.eclipse.jdt.internal.ui.javaeditor.ASTProvider@22881b1c
org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl#service -> org.eclipse.jdt.ui
java.lang.Object[289] -> {org.eclipse.osgi.service.debug.DebugOptionsListener}={listener.symbolic.name=org.eclipse.jdt.ui, s
java.util.ArrayList#elementData -> [Ljava.lang.Object;@498d7c57
org.eclipse.osgi.internal.serviceregistry.ServiceRegistry#allPublishedServices -> [{org.eclipse.osgi.framework.log.FrameworkLog}={service.id=4, service.bundleid=0, service.scope=bun
org.eclipse.osgi.internal.framework.EquinoxContainer#serviceRegistry -> org.eclipse.osgi.internal.serviceregistry.ServiceRegistry@1400984b
org.eclipse.osgi.internal.loader.BundleLoader#container -> Equinox Container: 133b45d6-7b15-4608-8c5d-5b237fa707e5
org.eclipse.osgi.internal.loader.EquinoxClassLoader#delegate -> org.eclipse.jdt.ui.tests_3.15.200.v20231101-2346
org.eclipse.osgi.internal.loader.EquinoxClassLoader -> org.eclipse.osgi.internal.loader.EquinoxClassLoader@728b62f1[org.eclipse.jdt.ui.tests:3.15.200.v202

Element 1
org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitEditor
org.eclipse.ui.texteditor.TextEditorAction#fTextEditor -> org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitEditor@47fe61bc
org.eclipse.jface.commands.ActionHandler#action -> org.eclipse.jdt.internal.ui.javaeditor.ClipboardOperationAction@1f51040d
org.eclipse.ui.internal.handlers.E4HandlerProxy#handler -> ActionHandler(org.eclipse.jdt.internal.ui.javaeditor.ClipboardOperationAction@1f51040d)
org.eclipse.e4.core.commands.internal.HandlerServiceHandler#currentStateHandler -> E4HandlerProxy [handler=ActionHandler(org.eclipse.jdt.internal.ui.javaeditor.ClipboardOperationActi
org.eclipse.core.commands.Command#handler -> WorkbenchHandlerServiceHandler("org.eclipse.ui.edit.cut")
org.eclipse.core.commands.ParameterizedCommand#command -> Command(org.eclipse.ui.edit.cut,Cut,
Cut the selection to the clipboard,
Category(org.eclipse.u
org.eclipse.jface.bindings.Binding#command -> ParameterizedCommand(Command(org.eclipse.ui.edit.cut,Cut,
Cut the selection to the clipboard,
C
org.eclipse.jface.bindings.Binding[140] -> Binding(COMMAND+X,
ParameterizedCommand(Command(org.eclipse.ui.edit.cut,Cut,
Cut the selection t
org.eclipse.jface.bindings.BindingManager#bindings -> [Lorg.eclipse.jface.bindings.Binding;@cfef34
org.eclipse.ui.internal.Workbench#bindingManager -> org.eclipse.jface.bindings.BindingManager@3667faa8
org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl#service -> org.eclipse.ui.internal.Workbench@320bfc61
java.lang.Object[228] -> {org.eclipse.ui.IWorkbench}={service.id=234, service.bundleid=283, service.scope=singleton, id=9b95
java.util.ArrayList#elementData -> [Ljava.lang.Object;@498d7c57
org.eclipse.osgi.internal.serviceregistry.ServiceRegistry#allPublishedServices -> [{org.eclipse.osgi.framework.log.FrameworkLog}={service.id=4, service.bundleid=0, service.scope=bun
org.eclipse.osgi.internal.framework.EquinoxContainer#serviceRegistry -> org.eclipse.osgi.internal.serviceregistry.ServiceRegistry@1400984b
org.eclipse.osgi.internal.loader.BundleLoader#container -> Equinox Container: 133b45d6-7b15-4608-8c5d-5b237fa707e5
org.eclipse.osgi.internal.loader.EquinoxClassLoader#delegate -> org.eclipse.jdt.ui.tests_3.15.200.v20231101-2346
org.eclipse.osgi.internal.loader.EquinoxClassLoader -> org.eclipse.osgi.internal.loader.EquinoxClassLoader@728b62f1[org.eclipse.jdt.ui.tests:3.15.200.v202

. Actual: 0
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.failEquals(Assert.java:187)
at org.junit.Assert.assertNotEquals(Assert.java:201)
at org.eclipse.jdt.ui.leaktest.LeakTestCase.assertInstanceCount(LeakTestCase.java:129)
at org.eclipse.jdt.ui.tests.leaks.JavaLeakTest.testJavaEditorBreadcrumbCloseOneOfTwo2(JavaLeakTest.java:263)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

i can not run the test locally .. failing with

```
java.lang.RuntimeException: JVM settings for --add-modules, --add-opens, and --illegal-access are probably missing.
Exception : 
Unable to make field transient java.util.HashMap$Node[] java.util.HashMap.table accessible: module java.base does not "opens java.util" to unnamed module @13edc1bc
	at org.eclipse.jdt.ui.leaktest.reftracker.ReferenceTracker.setAccessible(ReferenceTracker.java:113)
	at org.eclipse.jdt.ui.leaktest.reftracker.ReferenceTracker.followFieldReference(ReferenceTracker.java:70)
	at org.eclipse.jdt.ui.leaktest.reftracker.ReferenceTracker.visit(ReferenceTracker.java:151)
	at org.eclipse.jdt.ui.leaktest.reftracker.ReferenceTracker.start(ReferenceTracker.java:175)
	at org.eclipse.jdt.ui.leaktest.LeakTestCase.collect(LeakTestCase.java:58)
	at org.eclipse.jdt.ui.leaktest.LeakTestCase.assertInstanceCount(LeakTestCase.java:123)
	at org.eclipse.jdt.ui.tests.leaks.JavaLeakTest.testJavaEditorBreadcrumbCloseOneOfTwo2(JavaLeakTest.java:252)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field transient java.util.HashMap$Node[] java.util.HashMap.table accessible: module java.base does not "opens java.util" to unnamed module @13edc1bc
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at org.eclipse.jdt.ui.leaktest.reftracker.ReferenceTracker.setAccessible(ReferenceTracker.java:109)
	... 7 more
```

the error message is not explicit about what parameters to add

**Comment by iloveeclipse** [comment]
Should be fixed by https://github.com/eclipse-platform/eclipse.platform.ui/pull/1291

**Comment by jukzi** [comment]
The tests tries to walk the heap to see if there are leaks. We may need to remove the test in future as it is not possible to access private members with new JDKs anymore. Also there is no guarantee to garbage collection in time. Or rework by creating heapdumps and parsing them. But that seems to be an overkill.

**Comment by iloveeclipse** [comment]
Sure. Feel free to contribute :-) But so far the test works with Java 21, so it is good to have it.

BTW the test is green again, see https://download.eclipse.org/eclipse/downloads/drops4/I20231108-0600/testResults.php.

Closing.
