### ISSUE TITLE
NPE in ComplianceConfigurationBlock

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.ui#929]
check and uncheck "--release" option
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/92f4c1bb-ecde-4746-a2dd-7690f845c930)

```
java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.core.IJavaProject.getRawClasspath()" because the return value of "org.eclipse.jdt.core.JavaCore.create(org.eclipse.core.resources.IProject)" is null
	at org.eclipse.jdt.internal.ui.preferences.ComplianceConfigurationBlock.addsExportToSystemModule(ComplianceConfigurationBlock.java:867)
	at org.eclipse.jdt.internal.ui.preferences.ComplianceConfigurationBlock.validateSettings(ComplianceConfigurationBlock.java:652)
	at org.eclipse.jdt.internal.ui.preferences.OptionsConfigurationBlock.controlChanged(OptionsConfigurationBlock.java:866)
	at org.eclipse.jdt.internal.ui.preferences.OptionsConfigurationBlock$6.widgetSelected(OptionsConfigurationBlock.java:841)

```

**Comment by jukzi** [comment]
regression from 1bc6d924a977cff5faf6ff6abab7e51a622b1162
