### ISSUE TITLE
Javadoc view can not open

### ISSUE THREAD

**Issue by akurtakov** [eclipse-jdt/eclipse.jdt.ui#972]
Opening it shows broken state with the following details:
```
java.lang.NullPointerException: Cannot read field "red" because "val" is null
	at org.eclipse.jface.internal.text.html.HTMLPrinter.fromRGB(HTMLPrinter.java:66)
	at org.eclipse.jface.internal.text.html.HTMLPrinter.insertPageProlog(HTMLPrinter.java:140)
	at org.eclipse.jdt.internal.ui.infoviews.JavadocView.doSetInput(JavadocView.java:925)
	at org.eclipse.jdt.internal.ui.infoviews.JavadocView.refresh(JavadocView.java:767)
	at org.eclipse.jdt.internal.ui.infoviews.JavadocView.setForeground(JavadocView.java:748)
	at org.eclipse.jdt.internal.ui.infoviews.AbstractInfoView.inititalizeColors(AbstractInfoView.java:377)
	at org.eclipse.jdt.internal.ui.infoviews.AbstractInfoView.createPartControl(AbstractInfoView.java:235)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPartControl(CompatibilityPart.java:158)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityView.createPartControl(CompatibilityView.java:155)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:365)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	....

```

**Comment by akurtakov** [comment]
It is most likely caused by https://github.com/eclipse-platform/eclipse.platform.ui/pull/1334 . I'm looking into it.

**Comment by akurtakov** [comment]
Verified working in  I20231206-0410.
